config/routes.rb
InterpretersFrontend::Application.routes.draw do
  get "robots.txt" => "home#robots", format: :text, as: :robots
  get "sitemap.xml" => "home#sitemap", format: :xml, as: :sitemap
  get "/404", :to => "errors#error_404"
  get "/500", :to => "errors#error_500"
  put 'translated_review', to: 'client_reviews#translated_review'
  put 'original_review', to: 'client_reviews#original_review'
  
  get "/translations/:locale", to: "translations#show"

  scope "(:locale)", locale: /#{I18n.available_locales.join("|")}/ do
    spa_index = "spa#index"
    get "/spa_login", to: spa_index
    get "/translation", to: spa_index
    get "/translation_orders/new", to: spa_index
    get "/translation_orders/:id", to: spa_index
    get "/translation_orders/:id/completed", to: spa_index

    scope :spa, as: :spa do
      get "/", to: spa_index

      get "/searches", to: spa_index
      get "/searches/:id", to: spa_index
      get "/searches/:search_id/interpreters/:id", to: spa_index

      get "/orders", to: spa_index
      get "/orders/new", to: spa_index
      get "/orders/:id", to: spa_index
      get "/orders/:id/completed", to: spa_index

      get "/interpretation_calls", to: spa_index
      get "/interpretation_calls/new", to: spa_index
      get "/interpretation_calls/:id", to: spa_index

      get "/phone", to: spa_index
    end

    root :to => 'searches#new'

    # TODO: Move it to better place
    # get 'new_translation_order', to: 'translation_requests#new_translation_order', as: :new_translation_order
    # get 'show_translation_order', to: 'translation_requests#show_translation_order', as: :show_translation_order

    resource :personal_account, only: "show" do
      get "orders/:id", action: "show_order", as: :order
      get "orders/:id/voucher", action: :voucher, as: :voucher
      get "orders/:id/receipt", action: :receipt, as: :receipt
      get "orders/:id/invoice", action: :invoice, as: :invoice
      get "orders/:id/request_contacts", action: :request_contacts, as: :request_contacts
      get "searches", action: :searches, as: :searches
    end

    resource :jwt, only: "show"

    resources :call_promos, only: [:show]

    resources :interpretation_calls, only: [:index, :show, :new, :create] do
      member do
        get 'cancel'
        get 'start'
        get "complete"
        get "process_payment"
        scope module: :interpretation_calls do
          resource :duration, only: [:show]
          resource :external_numbers, only: [:create]
        end
      end
    end

    resource :twilio_token, only: [:show]

    resources :call_searches, controller: :interpretation_call_searches, only: [:new, :show, :create] do
      member do
        resources :available_questionnaires, only: [:index], module: :interpretation_call_searches
      end
    end

    resources :interpreter_inquiries, only: [:create]

    resources :partners, only: [:create]

    post 'orders/new', to: 'orders#new', as: :new_order
    get 'orders/new', to: 'orders#new'
    get 'orders/validate_email', to: 'orders#validate_email', as: :validate_email
    resources :orders, except: [:update, :destroy] do
      get 'complete', to: 'orders#complete', as: :complete
      get 'show_to_client', to: 'orders#show_to_client', as: :show_to_client
      member do
        post 'confirm_replacement'
        post 'cancel'
      end
    end

    scope :sms_service do
      post 'send_code', :to => 'orders#send_sms'
      post 'verification_code', :to => 'orders#verification_sms_code'
    end

    get '/searches/language_selector', to: 'searches#language_selector'
    get '/searches/your_language_selector', to: 'searches#your_language_selector'
    get '/searches', to: "searches#create"
    get '/new_partner_search', to: "searches#create"
    get '/amp/searches/update/:id', to: "searches#update", as: "amp_update_search"

    resources :searches do
      get 'partner_search_form', on: :collection
      post '/:id', action: :update, on: :collection
      get 'more_interpreters', to: 'searches#more_interpreters'
      get 'mini_more_interpreters', to: 'searches#mini_more_interpreters'
      get 'interpreter/:interpreter_id', to: 'searches#show_interpreter', as: :interpreter
    end

    resources :payments, only: [:new, :create]

    resources :client_reviews, only: [:update, :index]

    get 'payments/payonline/approve', to: 'payments#payonline_approve'
    get 'payments/payonline/decline', to: 'payments#payonline_decline'
    get 'payments/paypal/express_checkout/:order_id', to: "payments#paypal_express_checkout", as: :paypal_express_checkout_order
    get 'payments/paypal/complete/:order_id', to: 'payments#paypal_complete'
    get 'payments/braintree/sale/:order_id', to: 'payments#braintree_sale', as: :braintree_sale

    get 'payments/bluesnap/sale/:order_id', to: 'payments#bluesnap_sale', as: :bluesnap_sale
    #authenticated :user do
    #  root :to => 'home#dashboard', as: :authenticated_root
    #end

    # get 'dashboard', to: 'home#dashboard'
    get 'help', to: 'home#info'
    get 'help/about', to: 'home#about', as: :about
    get 'help/info', to: 'home#info', as: :info
    get 'help/help_interpreter', to: 'home#help_interpreter', as: :help_interpreter
    get 'interpreter_inquiries', to: 'home#help_interpreter'
    get 'help/for_clients', to: 'home#for_clients', as: :for_clients
    get 'help/for_affiliates', to: 'home#for_affiliates', as: :for_affiliates
    get 'help/terms_conditions', to: 'home#terms_conditions', as: :terms_conditions
    get 'help/services/guide', to: 'home#services_guide', as: :services_guide
    get 'help/services/escort_delegations', to: 'home#escort_delegations', as: :escort_delegations
    get 'help/services/interview', to: 'home#interview', as: :interview
    get 'help/services/clinic_consultation', to: 'home#clinic_consultation', as: :clinic_consultation
    get 'help/services/press_conferences', to: 'home#press_conferences', as: :press_conferences
    get 'help/services/support_individuals', to: 'home#support_individuals', as: :support_individuals
    get 'help/services/conversation', to: 'home#conversation', as: :conversation
    get 'help/services/presentation', to: 'home#presentation', as: :presentation
    get 'help/services/protocol_translation', to: 'home#protocol_translation', as: :protocol_translation
    get 'help/services/seminar_conference', to: 'home#seminar_conference', as: :seminar_conference
    get 'help/services/judicial_translation', to: 'home#judicial_translation', as: :judicial_translation
    get 'help/services/phone_talking', to: 'home#phone_talking', as: :phone_talking
    get 'help/services/celebrations', to: 'home#celebrations', as: :celebrations
    get 'help/services/exhibition', to: 'home#exhibition', as: :exhibition
    get 'help/privacy_policy', to: 'home#privacy_policy', as: :privacy_policy
    get 'help/support', to: 'client_support_tickets#new', as: :support
    get 'phone', to: 'home#phone', as: :phone

    get 'set_locale/:new_locale', to: "home#set_current_locale", as: :set_locale
    get 'set_current_currency/:currency', to: "home#set_current_currency", as: :set_current_currency

    resources :client_support_tickets, only: [:create]
    resources :interpreter_client_tickets, only: [:create]

    devise_for :users, controllers: { registrations: 'registrations', sessions: 'sessions'}

    resources :users
    post 'user_create_and_mail', to: 'users#create_and_mail'
    post 'interpreter_create_and_mail', to: 'interpreters#interpreter_create_and_mail'

    get ':city_name/:id', to: "searches#show", as: :search_city
    get ':city_name/:search_id/interpreter/:interpreter_id', to: "searches#show_interpreter", as: :search_interpreter_city
  end

  namespace :api do
    resources :tokens, only: [:create, :destroy]

    resources :countries, only: [:index] do
      get 'cities', to: 'countries#cities'
    end

    resources :cities do
      get 'interpreters', to: 'cities#interpreters'
    end
    get 'my_cities', to: 'cities#my_cities'


    # LISTS
    resources :service_types, only: [:index, :show]
    resources :languages, only: [:index, :show]
  end

  #get '/uploads/questionnaire/photo/:img/:img', to: redirect('/img/1.png')

end

app/controllers/personal_accounts_controller.rb
class PersonalAccountsController < ApplicationController
  before_filter :authenticate_user!

  def show
    @orders = current_user.orders
    if @orders.present?
      @orders = @orders.order(confirmation_date: :desc).includes({interpreter: :questionnaire}, :payment,:service_type, :currency)
                       .paginate(page: params[:page], per_page: 5)
    end 
  end

  def show_order
    @order = current_user.orders.find(params[:id])
    @search = @order.search
    @client_review = @order.client_review.try(:request?) ? @order.client_review : nil

    if @client_review and params[:review_score]
      @client_review.update_attribute(:score, params[:review_score]) if (1..5).include?(params[:review_score].to_i)
    end

    @interpreter = @order.interpreter
    @contacts_available = current_user.try(:interpreter_contacts_available?, @interpreter)
    @ticket = InterpreterClientTicket.new(search_id: @search.id)
    @ticket.messages.build
  end

  def request_contacts
    @order = current_user.orders.find(params[:id])
    if @order.can_request_contacts?
      @order.update_attribute(:free_cancellation_date, (Time.now - 1.minute))
    end
    redirect_to order_personal_account_path(@order), notice: t("flash_messages.contacts_requested")
  end

  def voucher
    @order = current_user.orders.find(params[:id])
    if @order.ready_for_presentation?
      respond_to do |format|
        format.pdf { render pdf: "Order ##{@order.id} voucher", template: "common_pdf_templates/voucher.html.erb", layout: false, encoding: "UTF-8" }
      end
    else
      redirect_to order_personal_account_path(@order), alert: I18n.t("voucher_not_ready", scope: :personal_account)
    end
  end

  def receipt
    @order = current_user.orders.find(params[:id])
    if @order.receipt_available?
      respond_to do |format|
        format.pdf { render pdf: "Order ##{@order.id} receipt", template: "common_pdf_templates/receipt.html.erb", layout: false}
      end
    else
      redirect_to order_personal_account_path(@order)
    end
  end

  def invoice
    @order = current_user.orders.find(params[:id])
    if @order.invoice_payment?
      respond_to do |f|
        f.pdf { render pdf: "#Order ##{@order.id} invoice", template: "common_pdf_templates/invoice.html.erb", layout: false}
      end
    else 
      redirect_to order_personal_account_path(@order)
    end
  end

  def searches
    return unless stringify_json_parameters("#{ENV['API_BASE_URL']}/searches/new.json", 'get', params)
    @searches = current_user.searches.order(created_at: :desc)
  end
end

app/helpers/personal_accounts_helper.rb
module PersonalAccountsHelper
end

app/views/personal_accounts/_interpreter_detail.html.haml
.cart_block
  - questionnaire = @interpreter.questionnaire
  - @questionnaire = questionnaire
  .photo-wrapper
    = image_tag questionnaire.photo_url, class: 'cart_photo'
  .info_wrapper
    .name #{l_questionnaire(:name)} #{l_questionnaire(:surname)}
    .prof
      = t("interpreter.title")
      %br
      %a.level.info_link.mobile-show{'data-id' => @questionnaire.id}
        %span.questionnaire-stars{class: questionnaire_stars_class(@questionnaire.score)}
    .right
      %a.experience_event.info_link{'data-id' => @questionnaire.id} #{t("interpreter.events")} (#{@questionnaire.experience_event_count})
      %br
      %a.recommendations.info_link{'data-id' => @questionnaire.id} #{t("interpreter.recommendations")}
      %br
      %a.experience.info_link{'data-id' => @questionnaire.id} #{t("interpreter.experience")} (#{t('years', count:  @questionnaire.experience_years)})
      %br
      - if @questionnaire.verified?
        %a.verified_profile.info_link.link-with-text{"data-text" => t("show_interpreter.verified_contacts_text")}
          = t("interpreter.verified_profile")
    .left
      %a.level.info_link.mobile-hide{'data-id' => @questionnaire.id}
        %span.questionnaire-stars{class: questionnaire_stars_class(@questionnaire.score)}
      %br
      %a.diplom.info_link{'data-id' => @questionnaire.id} #{t("interpreter.diplomas")} (#{@questionnaire.diplomas_count})
      %br
      %a.cert.info_link{'data-id' => @questionnaire.id} #{t("interpreter.certificates")} (#{@questionnaire.certificates_count})
      %br
      %a.verified_contacts.info_link.show_dialog{data: {dialog_id: "verified_contacts_dialog", dialog_title: t("show_interpreter.dialogs.profile_title")}}
        = t("interpreter.verified_contacts")
      #verified_contacts_dialog.my_dialog{style: "display:none;"}
        %h3.dialog-header= t("show_interpreter.dialogs.checked_and_confirmed")
        %p.check-text
          - if @contacts_available
            = t("show_interpreter.dialogs.email_full", email: @order.interpreter_email)
          - else 
            = t("show_interpreter.dialogs.email_address", domain: @order.interpreter_email.split('.').last)
        %p.check-text
          - if @contacts_available
            = t("show_interpreter.dialogs.phone_full", phone: @order.interpreter_phone)
          - else 
            = t("show_interpreter.dialogs.phone", last_two: @order.interpreter_phone.last(2))
        - unless @contacts_available
          %p
            - confirmation = link_to(t("show_interpreter.dialogs.order_confirmation"), "#available-serivces", class: "close-dialog", "data-close-dialog-id" => "verified_profile_dialog")
            = raw t("show_interpreter.dialogs.contacts_available", confirmation: confirmation)
  .clear
  = render "show_order_forms"
  .clear
  .desc
    = l_questionnaire :short_summary
  .desc
    = l_questionnaire :summary
.info_block
  .title= t("contact_details", @scope)
  %table
    %tr.email
      %td= t("email", @scope)
      %td
        - if @order.contacts_available_after_confirmation?
          = t("details_available_after_confirmation", @scope)
        - elsif @order.ready_for_presentation?
          = @order.interpreter_email
        - else
          = t("details_not_available", @scope)
          - if @order.can_request_contacts?
            %a.request_contacts{href: "#", data: {dialog_title: t("request_contacts", @scope), confirm_url: request_contacts_personal_account_path(@order)}}= t("request_contacts", @scope)
    %tr.phone
      %td= t("phone", @scope) 
      %td
        - if @order.contacts_available_after_confirmation?
          = t("details_available_after_confirmation", @scope)
        - elsif @order.ready_for_presentation?
          = @order.interpreter_phone
        - else 
          = t("details_not_available", @scope)
          - if @order.can_request_contacts?
            %a.request_contacts{href: "#", data: {dialog_title: t("request_contacts", @scope), confirm_url: request_contacts_personal_account_path(@order)}}= t("request_contacts", @scope)
- if @order.can_request_contacts?
  #request_contacts_dialog.my_dialog{style: "display:none;"}
    = t("request_contacts_text", @scope)
.info_block
  .title= t("service_info", @scope)
  %table
    %tr.languages
      %td= t("languages", @scope)
      %td= @order.language_pairs
    %tr.meeting_address
      %td= t("address", @scope)
      %td= @order.meeting_address
    %tr.additional_service
      %td= t("additional_services", @scope)
      %td= @order.additional_services || t("not_available", @scope)
    %tr
      %td= t("cancellation_conditions", @scope) 
      %td= raw @order.cancellation_conditions
- if @order.payment.present?
  .info_block
    .title= t("payment_info", @scope)
    %table
      %tr
        %td= t("payment", @scope)
        - if !@order.invoice_payment?
          %td= @order.payment_type(humanize: true)
      - if @order.invoice_payment?
        %tr
          %td= link_to @order.payment_type(humanize: true), invoice_personal_account_path(@order, format: :pdf), target: "_blank"
      %tr
        - if !@order.invoice_payment? and !@order.cash_payment?
          %td= t("payment_date", @scope)
          %td= @order.payment.formatted_created_at
      %tr
        %td
          = link_to t("get_receipt", @scope), receipt_personal_account_path(@order, format: :pdf), class: ("not_ready" if !@order.receipt_available?), 'data-target' => "#receipt_not_ready_modal"
          #receipt_not_ready_modal
            %p= t("receipt_not_ready", scope: :personal_account)
      - if @order.can_change_payment_method?
        %tr
          %td
            %span#load-payment-container= t("show_order_page.pay_with_card");
    #payment-container.payment-container-wide
.info_block
  .title= t("client_info.title", @scope)
  %table
    %tr.name
      %td= t("client_info.name", @scope)
      %td #{@order.client.name} #{@order.client.surname}
    %tr.phone
      %td= t("client_info.phone", @scope) 
      %td= @order.phone
    %tr.email
      %td= t("client_info.email", @scope) 
      %td= @order.client.email

:javascript
  $("body").on("click", "#load-payment-container", function() {
    $.get("/payments/new", {payment_type: "card", order_id: #{@order.id}, locale: "#{params[:locale]}"})
  });

- if params[:show_card_form]
  :javascript
    $(document).on('ready page:load', function() {
      $("#load-payment-container").click();
    });

app/views/personal_accounts/_order.html.haml
.my_view_block
  - questionnaire = order.interpreter.questionnaire
  = link_to order_personal_account_path(order) do
    = image_tag questionnaire.photo_url(:thumb), class: "img"
  .desc
    .order_info
      .price
        = order.payment.amount 
        = order.payment.currency.code
      .clearfix
      .number ##{order.id}
      .from #{t("orders_index_page.from")} #{order.from_date}
    = link_to "#{l_questionnaire(:name, questionnaire)} #{l_questionnaire(:surname, questionnaire)}", order_personal_account_path(order), class: "name"
    .details
      .info= order.service_type.to_s
      .time-range= order.selected_period
      .address= order.meeting_address 
      - if order.canceled?
        .red= t("orders_index_page.cancelled")
  .clear

app/views/personal_accounts/_order_details.html.haml
%table.order_details
  %tr
    %td.first= t("details", @scope)
    %td
      .id.red= @order.id
      .from 
        = t("from", @scope)
        .red= @order.from_date
      = link_to t("get_voucher", @scope), voucher_personal_account_path(@order, format: :pdf), 
                class: ("not_ready" unless @order.ready_for_presentation?), 'data-target' => "#voucher_not_ready_modal"
      #voucher_not_ready_modal
        - if @order.contacts_available_after_confirmation?
          %p= t("personal_account.voucher_ready_after_confirmation")
        - else 
          %p= t("voucher_not_ready", scope: :personal_account)
- if @order.canceled?
  %h3.red= t("cancelled", @scope)

app/views/personal_accounts/_show_order_forms.haml
- message_style = ("display:none;visibility:none;" unless params[:show_contact_form] )
- review_style = ("display:none;visibility:none;" unless params[:show_review_form] )
.info_wrapper_no_cart{style: "margin-top: 35px;"}
  - if defined?(additional_text)
    .wrap
      %span.mobile-hide= additional_text
  = link_to t("forms.send_message_to_int"), "#", class: "intranet-button fleft-button", "data-tab-target" => "#send-message-form"
  - if @client_review
    = link_to t("client_reviews.leave_review"), "#", class: "intranet-button leave-review",  "data-tab-target" => "#review-form"
  .clear
  .tabs 
    #send-message-form.base-form.tab{style: "width: 100%; #{message_style}"}
      = simple_form_for @ticket, as: :ticket, remote: true do |f|
        = f.input :search_id, as: :hidden
        = hidden_field_tag :recipient_id, @interpreter.id
        - unless user_signed_in?
          = f.input :name, label: false, input_html: {placeholder: t("forms.name"), class: 'base-input'}
          = f.input :email, label: false, input_html: {placeholder: t("forms.email"), class: 'base-input'}
          = f.input :phone, label: false, input_html: {placeholder: t("forms.phone"), class: 'base-input'}
        = f.simple_fields_for :messages do |f|
          = f.input :message, label: false, autofocus: true, input_html: {placeholder: t("forms.order_message"), class: 'base-input'}, as: :text
        .clear
        - unless user_signed_in?
          %label{style: "margin-top: 30px;"}
            = check_box_tag :send_to_all
            = t("forms.send_to_all")
        .clear
        = f.submit t("forms.send_button"), class: 'base-input-submit'
    - if @client_review

      #review-form.base-form.tab{style: "width: 100%; #{review_style}"}
        = simple_form_for @client_review, remote: true do |f|
          = f.input :score, label: false, input_html: {class: 'base-input', "data-connected-elem" => "#client-review-score-stars .raty-text"}, as: :hidden
          = f.input :interpretation_score, label: false, input_html: {class: 'base-input'}, as: :hidden
          = f.input :punctuality_score, label: false, input_html: {class: 'base-input'}, as: :hidden
          = f.input :consultation_score, label: false, input_html: {class: 'base-input'}, as: :hidden

          .raty-input-container#client-review-score-stars
            .raty-stars{"data-target" => "#client_review_score", "data-score" => @client_review.score}
            .raty-text= t("client_reviews.score")
          .raty-input-container
            .raty-stars{"data-target" => "#client_review_interpretation_score"}
            .raty-text= t("client_reviews.interpretation_score")
          .raty-input-container
            .raty-stars{"data-target" => "#client_review_punctuality_score"}
            .raty-text= t("client_reviews.punctuality_score")
          .raty-input-container
            .raty-stars{"data-target" => "#client_review_consultation_score"}
            .raty-text= t("client_reviews.consultation_score")

          = f.input :comment, label: false, autofocus: true, input_html: {placeholder: t("client_reviews.comment"), class: 'base-input'}, as: :text
          .clear
          = f.submit t("forms.send_button"), class: 'base-input-submit'

app/views/personal_accounts/_sidebar.html.haml
.cabinet_sidebar.mobile-hide
  %a.mob_menu= t("order_pages_sidebar.menu")
  %ul.cabinet_sidebar_menu
    %li= link_to t("order_pages_sidebar.orders"), personal_account_path, class: "cabinet_sidebar_menu1"
    %li= link_to t("order_pages_sidebar.searches"), searches_personal_account_path, class: "cabinet_sidebar_menu2"
    %li= link_to t("order_pages_sidebar.calls"), interpretation_calls_path, class: "cabinet_sidebar_menu_calls"
    %li= link_to t("order_pages_sidebar.logout"), destroy_user_session_path, class: "cabinet_sidebar_menu5", method: :delete

app/views/personal_accounts/receipt.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
   "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />

    <style>
      .colored{
        background: #FFC602;
        border: 1px solid;
        text-align: center;
      }
      .info{
        float: right;
        margin-top: 10px;
      }
      .title{
        font-size: 30px;
        margin: 0 30px;
        text-align: center;
        display: inline-block;
      }
      .header{
        margin: 10px 0;
      }
      .header{
        text-align: center;
      }
      .text{
        margin: 10px 0; 
      }
      .address{
        border-top: 1px solid; 
        margin: 10px 0;
        padding: 10px 0;
      }
      .reg-num{
        float: right;
      }
      .stamp{
        position: absolute;
        left: 50%;
        top: -70px;
      }
      .footer{
        position: relative;
      }
    </style>
  </head>
  <body>
    <div class="container">
      <div class="colored">interpreters.travel</div>
      <div class="info">
        <b>Receipt No:</b><%= @order.receipt_id %><br/>
        <b>DATE:</b> <%= @order.payment.created_at %>
      </div>
      <div class="header">
        <h1 class="title">Payment Receipt</h1>
      </div>
      <div class="text">
        <b>Received from:</b> 
        <% if @order.legal_form? %>
          <%= "#{@order.legal_form} #{@order.name}" %>
        <% else %>
          <%= "#{@order.name} #{@order.surname}" %>
        <% end %>
        <br/>
        <b>the amount of:</b> 
        <%= "#{@order.payment.amount}" "#{@order.payment.currency.code}" %> 
      </div>
      <div class="footer">
        <div class="stamp">
          <%= wicked_pdf_image_tag "stamp.png" %>
        </div>
        <span class="name">INTERPRETERS.TRAVEL OÜ</span>
        <span class="reg-num">Registration number: 16422855</span>    
        <div class="address">
          Registred office: Harju maakond, Tallinn, Kesklinna linnaosa, Vesivärava tn 50-201, 10152. Office phone: +357 22 008 050. Email: office@interpreters.travel
       </div>
      </div>
    </div>
</body>

app/views/personal_accounts/searches.html.haml
- provide :description, t("searches_index_page.title")
- content_for :body do
  .main_content
    = render "sidebar"
    .cabinet_content
      .mob_title
        = t("searches_index_page.title")
      .search-form-container{style: "text-align: left; margin-top: 15px; margin-bottom: 15px;"}
        .search-form-link
          = link_to "#search-form", "data-replace-with" => ".call-search-form", style: "text-decoration: none;" do
            .loading-bar= t("searches_index_page.show_search_form")
          .call-search-form{style: "display:none"}= render 'searches/search_form'
      .clear
      .my_view_wrapper
        - if @searches.present?
          .is_cont
            %table.searches
              %thead
                %tr
                  %th.created_at= t("searches_index_page.created_at")
                  %th.city= t("searches_index_page.city")
                  %th.language_pair= t("searches_index_page.languages")
                  %th.intervals= t("searches_index_page.intervals")
              %tbody
                - @searches.each do |search|
                  %tr{onclick: "Turbolinks.visit('#{search_path(search.id)}')"}
                    %td= search.created_at.strftime("%d.%m, %m:%H")
                    %td= search.city.to_s
                    %td= search.language_pair_text
                    %td= search.intervals_text.split(",").map(&:strip).join("<br>").html_safe

    .clear
  :scss
    #search_language_id-styler .jq-selectbox__select {
      line-height: 34px !important;
      height: 50px !important;
    }
    #search_language_id-styler .jq-selectbox__trigger-arrow {
      top: 21px !important;
    }
    @media screen and (min-width: 768px) {
      .result {
        margin: 10px 10px 5px -27px !important;
        width: 225px !important;
      }
      .find_translator_wrapper .form_wrapper .label input.find_translator_city {
        height: 32px !important;
      }
    }

app/views/personal_accounts/show.html.haml
- provide :description, t("orders_index_page.title")
- content_for :head do
  = javascript_include_tag "https://bluesnap.com/source/web-sdk/bluesnap.js"
- content_for :body do
  .main_content
    .main-page-sidebar= render "sidebar"
    .cabinet_content
      .mob_title
        = t("orders_index_page.title")
      .my_view_wrapper
        - if @orders.present?
          .is_cont
            = render partial: "order", collection: @orders
          - unless @orders.current_page >= @orders.total_pages
            = link_to personal_account_path(page: @orders.current_page + 1), remote: true, class: "load-more" do
              .loading-bar= t("orders_index_page.load_more")
    .clear

app/views/personal_accounts/show.js.erb
$(".is_cont").append("<%= j render partial: 'order', collection: @orders %>");
<% if @orders.present? %>
  $(".load-more").attr("href", "<%= personal_account_path(page: params[:page].to_i + 1) %>");
<% else %>
  $(".load-more").hide();
<% end %>

app/views/personal_accounts/show_order.html.haml
- @scope = {scope: :show_order_page}
- provide :description, t("title", @scope)
- content_for :head do
  = javascript_include_tag "https://bluesnap.com/source/web-sdk/bluesnap.js"
- content_for :body do
  .green_line
  .main_content
    = render 'shared/flash_messages'
    = render "sidebar"
    .cart_content
      = render "order_details"
      .cart_country_wrapper
        .country #{@search.city.country.to_s}, #{@search.city.name}
        #{t("period", @scope)} #{@order.selected_period}

      = render 'interpreter_detail'
      - if current_user.is_client? && @order.awaiting_client_confirmation?
        = link_to confirm_replacement_order_path(@order), class: "load-more", method: :post do 
          .loading-bar= t("confirm_order_changes", @scope)
      - if @order.cancellation_possible?
        = link_to "#", class: "load-more", id: "order_cancel" do
          .loading-bar.bg-danger= t("cancel_order", @scope)

        #order_cancel_modal
          %p 
            %b= t("cancel_warning", @scope)
          %p= link_to t("continue", @scope), cancel_order_path(@order), class: "btn", method: :post