config/routes.rb
InterpretersFrontend::Application.routes.draw do
  get "robots.txt" => "home#robots", format: :text, as: :robots
  get "sitemap.xml" => "home#sitemap", format: :xml, as: :sitemap
  get "/404", :to => "errors#error_404"
  get "/500", :to => "errors#error_500"
  put 'translated_review', to: 'client_reviews#translated_review'
  put 'original_review', to: 'client_reviews#original_review'
  
  get "/translations/:locale", to: "translations#show"

  scope "(:locale)", locale: /#{I18n.available_locales.join("|")}/ do
    spa_index = "spa#index"
    get "/spa_login", to: spa_index
    get "/translation", to: spa_index
    get "/translation_orders/new", to: spa_index
    get "/translation_orders/:id", to: spa_index
    get "/translation_orders/:id/completed", to: spa_index

    scope :spa, as: :spa do
      get "/", to: spa_index

      get "/searches", to: spa_index
      get "/searches/:id", to: spa_index
      get "/searches/:search_id/interpreters/:id", to: spa_index

      get "/orders", to: spa_index
      get "/orders/new", to: spa_index
      get "/orders/:id", to: spa_index
      get "/orders/:id/completed", to: spa_index

      get "/interpretation_calls", to: spa_index
      get "/interpretation_calls/new", to: spa_index
      get "/interpretation_calls/:id", to: spa_index

      get "/phone", to: spa_index
    end

    root :to => 'searches#new'

    # TODO: Move it to better place
    # get 'new_translation_order', to: 'translation_requests#new_translation_order', as: :new_translation_order
    # get 'show_translation_order', to: 'translation_requests#show_translation_order', as: :show_translation_order

    resource :personal_account, only: "show" do
      get "orders/:id", action: "show_order", as: :order
      get "orders/:id/voucher", action: :voucher, as: :voucher
      get "orders/:id/receipt", action: :receipt, as: :receipt
      get "orders/:id/invoice", action: :invoice, as: :invoice
      get "orders/:id/request_contacts", action: :request_contacts, as: :request_contacts
      get "searches", action: :searches, as: :searches
    end

    resource :jwt, only: "show"

    resources :call_promos, only: [:show]

    resources :interpretation_calls, only: [:index, :show, :new, :create] do
      member do
        get 'cancel'
        get 'start'
        get "complete"
        get "process_payment"
        scope module: :interpretation_calls do
          resource :duration, only: [:show]
          resource :external_numbers, only: [:create]
        end
      end
    end

    resource :twilio_token, only: [:show]

    resources :call_searches, controller: :interpretation_call_searches, only: [:new, :show, :create] do
      member do
        resources :available_questionnaires, only: [:index], module: :interpretation_call_searches
      end
    end

    resources :interpreter_inquiries, only: [:create]

    resources :partners, only: [:create]

    post 'orders/new', to: 'orders#new', as: :new_order
    get 'orders/new', to: 'orders#new'
    get 'orders/validate_email', to: 'orders#validate_email', as: :validate_email
    resources :orders, except: [:update, :destroy] do
      get 'complete', to: 'orders#complete', as: :complete
      get 'show_to_client', to: 'orders#show_to_client', as: :show_to_client
      member do
        post 'confirm_replacement'
        post 'cancel'
      end
    end

    scope :sms_service do
      post 'send_code', :to => 'orders#send_sms'
      post 'verification_code', :to => 'orders#verification_sms_code'
    end

    get '/searches/language_selector', to: 'searches#language_selector'
    get '/searches/your_language_selector', to: 'searches#your_language_selector'
    get '/searches', to: "searches#create"
    get '/new_partner_search', to: "searches#create"
    get '/amp/searches/update/:id', to: "searches#update", as: "amp_update_search"

    resources :searches do
      get 'partner_search_form', on: :collection
      post '/:id', action: :update, on: :collection
      get 'more_interpreters', to: 'searches#more_interpreters'
      get 'mini_more_interpreters', to: 'searches#mini_more_interpreters'
      get 'interpreter/:interpreter_id', to: 'searches#show_interpreter', as: :interpreter
    end

    resources :payments, only: [:new, :create]

    resources :client_reviews, only: [:update, :index]

    get 'payments/payonline/approve', to: 'payments#payonline_approve'
    get 'payments/payonline/decline', to: 'payments#payonline_decline'
    get 'payments/paypal/express_checkout/:order_id', to: "payments#paypal_express_checkout", as: :paypal_express_checkout_order
    get 'payments/paypal/complete/:order_id', to: 'payments#paypal_complete'
    get 'payments/braintree/sale/:order_id', to: 'payments#braintree_sale', as: :braintree_sale

    get 'payments/bluesnap/sale/:order_id', to: 'payments#bluesnap_sale', as: :bluesnap_sale
    #authenticated :user do
    #  root :to => 'home#dashboard', as: :authenticated_root
    #end

    # get 'dashboard', to: 'home#dashboard'
    get 'help', to: 'home#info'
    get 'help/about', to: 'home#about', as: :about
    get 'help/info', to: 'home#info', as: :info
    get 'help/help_interpreter', to: 'home#help_interpreter', as: :help_interpreter
    get 'interpreter_inquiries', to: 'home#help_interpreter'
    get 'help/for_clients', to: 'home#for_clients', as: :for_clients
    get 'help/for_affiliates', to: 'home#for_affiliates', as: :for_affiliates
    get 'help/terms_conditions', to: 'home#terms_conditions', as: :terms_conditions
    get 'help/services/guide', to: 'home#services_guide', as: :services_guide
    get 'help/services/escort_delegations', to: 'home#escort_delegations', as: :escort_delegations
    get 'help/services/interview', to: 'home#interview', as: :interview
    get 'help/services/clinic_consultation', to: 'home#clinic_consultation', as: :clinic_consultation
    get 'help/services/press_conferences', to: 'home#press_conferences', as: :press_conferences
    get 'help/services/support_individuals', to: 'home#support_individuals', as: :support_individuals
    get 'help/services/conversation', to: 'home#conversation', as: :conversation
    get 'help/services/presentation', to: 'home#presentation', as: :presentation
    get 'help/services/protocol_translation', to: 'home#protocol_translation', as: :protocol_translation
    get 'help/services/seminar_conference', to: 'home#seminar_conference', as: :seminar_conference
    get 'help/services/judicial_translation', to: 'home#judicial_translation', as: :judicial_translation
    get 'help/services/phone_talking', to: 'home#phone_talking', as: :phone_talking
    get 'help/services/celebrations', to: 'home#celebrations', as: :celebrations
    get 'help/services/exhibition', to: 'home#exhibition', as: :exhibition
    get 'help/privacy_policy', to: 'home#privacy_policy', as: :privacy_policy
    get 'help/support', to: 'client_support_tickets#new', as: :support
    get 'phone', to: 'home#phone', as: :phone

    get 'set_locale/:new_locale', to: "home#set_current_locale", as: :set_locale
    get 'set_current_currency/:currency', to: "home#set_current_currency", as: :set_current_currency

    resources :client_support_tickets, only: [:create]
    resources :interpreter_client_tickets, only: [:create]

    devise_for :users, controllers: { registrations: 'registrations', sessions: 'sessions'}

    resources :users
    post 'user_create_and_mail', to: 'users#create_and_mail'
    post 'interpreter_create_and_mail', to: 'interpreters#interpreter_create_and_mail'

    get ':city_name/:id', to: "searches#show", as: :search_city
    get ':city_name/:search_id/interpreter/:interpreter_id', to: "searches#show_interpreter", as: :search_interpreter_city
  end

  namespace :api do
    resources :tokens, only: [:create, :destroy]

    resources :countries, only: [:index] do
      get 'cities', to: 'countries#cities'
    end

    resources :cities do
      get 'interpreters', to: 'cities#interpreters'
    end
    get 'my_cities', to: 'cities#my_cities'


    # LISTS
    resources :service_types, only: [:index, :show]
    resources :languages, only: [:index, :show]
  end

  #get '/uploads/questionnaire/photo/:img/:img', to: redirect('/img/1.png')

end

app/controllers/home_controller.rb
 class HomeController < ApplicationController
  #before_filter :authenticate_user!, except: [:help]
  #layout 'intranet'

  layout 'application'

  def sitemap
    path = Rails.root.join("public", "sitemaps", "sitemap.xml")
    if File.exists?(path)
      render xml: open(path).read
    else
      render text: "Sitemap not found.", status: :not_found
    end
  end

  def robots
    render 'robots.text'
  end

  def dashboard
  end

  def set_current_locale
    url = (request.referer || root_url(locale: nil))
    cookies[:locale] = { value: params[:new_locale], expires: 90.days.from_now }
    redirect_to current_url_with_locale(params[:new_locale], url)
  end 

  def set_current_currency
    c = params[:currency]
    session[:current_currency] = c.to_s.upcase
    redirect_to (request.referer || root_path)
  end 

  def help
  end

  def help_interpreter
    @interpreter_inquiry ||= InterpreterInquiry.new
    @reviews = InterpreterReview.order("RANDOM()").limit(20)
  end

  def for_affiliates
  end

  def about
  end

  def info
    set_cities_countries_count(round: true)
  end

  def for_clients
    @reviews = ClientReview.for_current_locale
    set_cities_countries_count
  end

  def services_guide
  end

  def escort_delegations
  end

  def interview
  end

  def clinic_consultation
  end

  def press_conferences
  end

  def support_individuals
  end

  def conversation
  end

  def presentation
  end

  def protocol_translation
  end

  def seminar_conference
  end

  def judicial_translation
  end

  def phone_talking
  end

  def celebrations
  end

  def privacy_policy
  end

  def terms_conditions
  end

  def phone
    @interpreter_inquiry ||= InterpreterInquiry.new
  end
end

app/helpers/home_helper.rb
module HomeHelper
  # You can specify array of images which will be rendered in order or number of images to render. Make sure to add required files in assets/images/help/img/#{locale}/YourImageName#{number}.jpg
  # For example: Search1.jpg, Search2.jpg, Search3.jpg will be rendered for {search: 3} 
  # There are different images for each locale, you can see the translations in config/help_pages.locale.yml
  HELP_PAGE_IMAGES = {
    ru: {search: 3, filter: 5, view: 3, order: 7, payment: ['MastercardVISA.jpg', 'Payment1.jpg', 'bank.jpg', "Payment2.jpg", 'helper_ico_01.png', 'helper_ico_02.png', 'helper_ico_03.png', "Payment3.jpg", "Payment4.jpg", "Payment5.jpg"], cabinet: 2},
    en: {search: 3, filter: 5, view: 3, order: 6, payment: ['MastercardVISA.jpg', 'Payment1.jpg', 'bank.jpg', "Payment2.jpg", 'helper_ico_01.png', 'helper_ico_02.png'], cabinet: 2},
    de: {search: 3, filter: 5, view: 3, order: 6, payment: ['MastercardVISA.jpg', 'Payment1.png', 'bank.jpg', "Payment2.png", 'helper_ico_01.png', 'helper_ico_02.png'], cabinet: 2},
    zh: {search: 3, filter: 5, view: 3, order: 6, payment: ['MastercardVISA.jpg', 'Payment1.jpg', 'bank.jpg', "Payment2.jpg", 'helper_ico_01.png', 'helper_ico_02.png'], cabinet: 2},
    fr: {search: 3, filter: 5, view: 3, order: 6, payment: ['MastercardVISA.jpg', 'Payment1.jpg', 'bank.jpg', "Payment2.jpg", 'helper_ico_01.png', 'helper_ico_02.png'], cabinet: 2},
    es: {search: 3, filter: 5, view: 3, order: 6, payment: ['MastercardVISA.jpg', 'Payment1.jpg', 'bank.jpg', "Payment2.jpg", 'helper_ico_01.png', 'helper_ico_02.png'], cabinet: 2},
    it: {search: 3, filter: 5, view: 3, order: 6, payment: ['MastercardVISA.jpg', 'Payment1.jpg', 'bank.jpg', "Payment2.jpg", 'helper_ico_01.png', 'helper_ico_02.png'], cabinet: 2}

  }

  HELP_PAGE_IMAGES.each do |locale,hash| 
    directory = "help/img/#{locale}"
    hash.each do |k, v|
      new_value = if v.is_a?(Array)
        v.map {|img| "#{directory}/#{img}"}
      else 
        images = []
        img_path = "#{directory}/#{k.to_s.capitalize}"
        v.times {|t| images << "#{img_path}#{t+1}.jpg"}
        images
      end
      hash[k] = new_value
    end
  end

  def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end

  def active_link_to(link_text, link_path, my_action_name)
    if action_name.eql? my_action_name
      content_tag :li, class: 'current' do
        link_to link_text, link_path
      end
    else
      content_tag :li do
        link_to link_text, link_path
      end
    end
  end

  def help_page_images
    HELP_PAGE_IMAGES[I18n.locale] || HELP_PAGE_IMAGES[:en]
  end

end

app/views/home/_goto_search_button.html.haml
= link_to t("help_menu.find_interpreter"), root_path, class: 'intranet-button'

app/views/home/_help_menu.html.haml
%ul.about_sidebar_menu
  = active_link_to t("help_menu.info"), info_path, 'info'
  = active_link_to t("help_menu.for_clients"), for_clients_path, 'for_clients'
  = active_link_to t("help_menu.for_interpreters"), help_interpreter_path, 'help_interpreter'
  = active_link_to t("help_menu.for_affiliates"), for_affiliates_path, 'for_affiliates'

  - all_service = %W(services_guide escort_delegations interview exhibition celebrations seminar_conference phone_talking judicial_translation clinic_consultation press_conferences support_individuals conversation presentation protocol_translation)
  %li{class: "#{'current_parrent' if all_service.include? action_name }"}
    %a{:href => '#'}= t("help_menu.service_types")
    %ul
      = active_link_to t("service_types.conversation"), conversation_path, 'conversation'
      = active_link_to t("service_types.exhibition"), exhibition_path, 'exhibition'
      = active_link_to t("service_types.seminar"), seminar_conference_path, 'seminar_conference'
      = active_link_to t("service_types.presentation"), presentation_path, 'presentation'
      = active_link_to t("service_types.clinic"), clinic_consultation_path, 'clinic_consultation'
      = active_link_to t("service_types.celebration"), celebrations_path, 'celebrations'
      = active_link_to t("service_types.guide"), services_guide_path, 'services_guide'
      = active_link_to t("service_types.delegations_escort"), escort_delegations_path, 'escort_delegations'
      = active_link_to t("service_types.individuals"), support_individuals_path, 'support_individuals'
      = active_link_to t("service_types.phone_talking"), phone_talking_path, 'phone_talking'
      = active_link_to t("service_types.interview"), interview_path, 'interview'
      = active_link_to t("service_types.press_conference"), press_conferences_path, 'press_conferences'
      = active_link_to t("service_types.protocol_translation"), protocol_translation_path, 'protocol_translation'
      = active_link_to t("service_types.judicial_translation"), judicial_translation_path, 'judicial_translation'
  = active_link_to t("help_menu.calls"), phone_path, "phone"
  = active_link_to t("help_menu.support"), support_path, 'support'
  = active_link_to t("help_menu.terms"), terms_conditions_path, 'terms_conditions'
  = active_link_to t("help_menu.privacy_policy"), privacy_policy_path, 'privacy_policy'
  = active_link_to t("help_menu.about"), about_path, 'about'

app/views/home/about.html.haml
- content_for :description do
  .mobile-hide= t("about_page.title")

- content_for :title do
  = t("about_page.title")

- content_for :meta_description do
  = t("meta_desc.about")

- content_for :back_link do
  = link_to t("help_menu.back_link"), root_path, class: 'back_link'

- content_for :body do
  .main_content
    .about_sidebar
      = render partial: 'home/help_menu'
    .cabinet_content
      .about_content
        .about_article
          %p
            = raw t("about_page.addresses.title")
          %p
            = raw t("about_page.addresses.estonia")
            .leaflet-static-map{"data-lat" => "59.43275361", "data-lng" => "24.7796325"}
    .clear
      .clear

app/views/home/celebrations.html.haml
- content_for :description do
  .mobile-hide= t("service_types.title")

- [:meta_description, :title].each do |n|
  - content_for n do
    = t("service_pages.celebration.title") 

- content_for :meta_description do
  = t("service_pages.celebration.title") 

- content_for :back_link do
  = link_to t("help_menu.back_link"), root_path, class: 'back_link'

- content_for :body do
  .main_content
    .about_sidebar
      = render partial: 'home/help_menu'
    .about_content
      .about_type_img_wrapper
        = image_tag 'help/torj.png', class: 'img', alt: ''
        .text
          .text_inner= t("service_pages.celebration.title")
      .about_article= raw t("service_pages.celebration.text")
      = render 'goto_search_button'
    .clear

app/views/home/dashboard.html.haml
- content_for :description do
  My viewings


- content_for :body do
  .main_content
    .my_view_wrapper
      .is_cont
        .my_view_block
          %a{href: "#"}
            %img.img{src: "img/cabinet_img_01.png", alt: ''}/
          .desc
            %a.name{href: "#"} Hans Itka
            .mob_price 10 100 rub
            %a.mob_level{href: "#"}
              Level summary
              %span 8.1
            .text The diplomaed translator, the philologist. I carry out interpretations in the state. establishments: in department for foreigners in Berlin, in the head customs office; in lawyer and notary offices, at the doctor.
            .links
              %a.rating{href: "#"} Well (8.3)
              %a.comment{href: "#"} 15 reviews
              %a.level{href: "#"}
                Level summary
                %span 8.1
          .clear
        .my_view_block
          %a{href: "#"}
            %img.img{src: "img/cabinet_img_01.png", alt: ''}/
          .desc
            %a.name{href: "#"} Hans Itka
            .mob_price 10 100 rub
            %a.mob_level{href: "#"}
              Level summary
              %span 8.1
            .text The diplomaed translator, the philologist. I carry out interpretations in the state. establishments: in department for foreigners in Berlin, in the head customs office; in lawyer and notary offices, at the doctor.
            .links
              %a.rating{href: "#"} Well (8.3)
              %a.comment{href: "#"} 15 reviews
              %a.level{href: "#"}
                Level summary
                %span 8.1
          .clear
        .my_view_block
          %a{href: "#"}
            %img.img{src: "img/cabinet_img_01.png, alt: ''"}/
          .desc
            %a.name{href: "#"} Hans Itka
            .mob_price 10 100 rub
            %a.mob_level{href: "#"}
              Level summary
              %span 8.1
            .text The diplomaed translator, the philologist. I carry out interpretations in the state. establishments: in department for foreigners in Berlin, in the head customs office; in lawyer and notary offices, at the doctor.
            .links
              %a.rating{href: "#"} Well (8.3)
              %a.comment{href: "#"} 15 reviews
              %a.level{href: "#"}
                Level summary
                %span 8.1
          .clear
        .my_view_block
          %a{href: "#"}
            %img.img{src: "img/cabinet_img_01.png", alt: ''}/
          .desc
            %a.name{href: "#"} Hans Itka
            .mob_price 10 100 rub
            %a.mob_level{href: "#"}
              Level summary
              %span 8.1
            .text The diplomaed translator, the philologist. I carry out interpretations in the state. establishments: in department for foreigners in Berlin, in the head customs office; in lawyer and notary offices, at the doctor.
            .links
              %a.rating{href: "#"} Well (8.3)
              %a.comment{href: "#"} 15 reviews
              %a.level{href: "#"}
                Level summary
                %span 8.1
          .clear
        .my_view_block
          %a{href: "#"}
            %img.img{src: "img/cabinet_img_01.png", alt: ''}/
          .desc
            %a.name{href: "#"} Hans Itka
            .mob_price 10 100 rub
            %a.mob_level{href: "#"}
              Level summary
              %span 8.1
            .text The diplomaed translator, the philologist. I carry out interpretations in the state. establishments: in department for foreigners in Berlin, in the head customs office; in lawyer and notary offices, at the doctor.
            .links
              %a.rating{href: "#"} Well (8.3)
              %a.comment{href: "#"} 15 reviews
              %a.level{href: "#"}
                Level summary
                %span 8.1
          .clear

    .clear

app/views/home/escort_delegations.html.haml
- content_for :description do
  .mobile-hide= t("service_types.title")

- [:meta_description, :title].each do |n|
  - content_for n do
    = t("service_pages.delegations.title")

- content_for :back_link do
  = link_to t("help_menu.back_link"), root_path, class: 'back_link'

- content_for :body do
  .main_content
    .about_sidebar
      = render partial: 'home/help_menu'
    .about_content
      .about_type_img_wrapper
        = image_tag 'help/deleg.png', class: 'img', alt: ''
        .text
          .text_inner= t("service_pages.delegations.title")
      .about_article= raw t("service_pages.delegations.text")
      = render 'goto_search_button'
    .clear

app/views/home/for_affiliates.haml
- content_for :description do
  .mobile-hide= t("for_affiliates_page.title")

- content_for :title do
  = t("for_affiliates_page.title")

- content_for :meta_description do 
  = t("meta_desc.for_affiliates")

- content_for :intranet_button do
  %a.intranet-button.mobile-hide{href: for_affiliates_path(anchor: "affiliate_form")}
    = t("for_affiliates_page.signup_link")
  %a.intranet-button.mobile-hide{href: ENV["BACKEND_URL"]}
    = t("for_affiliates_page.login")

- content_for :back_link do
  = link_to t("help_menu.back_link"), root_path, class: 'back_link'

- content_for :body do
  .main_content
    .about_sidebar
      = render partial: 'home/help_menu'
    .about_content
      %h1.text-header= t("for_affiliates_page.page_title")
      %p{style: 'font: 14px/17px "robotolight"'}= t("for_affiliates_page.description")
      .about_article
        %h2= t("for_affiliates_page.block1.title")
        .step_wrapper
          .step
            .num
              1
            .text
              = t("for_affiliates_page.block1.step1")
            .clear
          .step
            .num
              2
            .text
              = t("for_affiliates_page.block1.step2")
            .clear
          .step
            .num
              3
            .text
              = t("for_affiliates_page.block1.step3")
            .clear
        %h2= t("for_affiliates_page.block2.title")
        %p= raw t("for_affiliates_page.block2.text")

        %h2= t("for_affiliates_page.block3.title")
        %p= raw t("for_affiliates_page.block3.text")

        %h2= t("for_affiliates_page.block4.title")
        %p{style: ("color: green; font-weight: bold;" if params[:partner])} 
          = t("for_affiliates_page.block4.step1")
          - if params[:partner]
            %i.base-input-success-icon{style: "float:none; margin:0; display: inline-block"}
        %p= t("for_affiliates_page.block4.step2")
        %p= t("for_affiliates_page.block4.step3")
        - if notice
          %p#notice= notice

        #affiliate_form{style: "margin-top: 40px;"}
          - if params[:partner]
            %div
              %p= t("for_affiliates_page.after_reg.text")
              = link_to t("for_affiliates_page.after_reg.link"), "#{ENV['BACKEND_URL']}/partner_accounts/#{params[:partner]}/edit", class: "intranet-button questionnaire-button"
          - else 
            .begin_form= render("partners/form")
    .clear

app/views/home/interview.html.haml
- content_for :description do
  .mobile-hide= t("service_types.title")

- [:meta_description, :title].each do |n|
  - content_for n do
    = t("service_pages.interview.title")

- content_for :back_link do
  = link_to t("help_menu.back_link"), root_path, class: 'back_link'

- content_for :body do
  .main_content
    .about_sidebar
      = render partial: 'home/help_menu'
    .about_content
      .about_type_img_wrapper
        = image_tag 'help/inter.png', class: 'img', alt: ''
        .text
          .text_inner= t("service_pages.interview.title")
      .about_article= raw t("service_pages.interview.text")
      = render 'goto_search_button'
    .clear

app/views/home/phone.html.haml
- content_for :description do
  .mobile-hide= t("for_phone_page.title")

- content_for :title do
  = t("for_phone_page.title")

- content_for :keywords do
  = t("for_phone_page.keywords")

- content_for :meta_description do 
  = t("meta_desc.phone")

- content_for :back_link do
  = link_to t("help_menu.back_link"), root_path, class: 'back_link'

- content_for :body do
  .main_content
    .about_sidebar.mobile-hide
      = render partial: 'home/help_menu'
    .about_content
      .about_for_trans_img_wrapper
        = image_tag 'help/phone.png', class: 'img', alt: ''
      .about_article
        %h2= t("for_phone_page.welcome")
        %ul
          %li= t("for_phone_page.ul.li_1")
          %li= t("for_phone_page.ul.li_2")
          %li= t("for_phone_page.ul.li_3")
          %li= t("for_phone_page.ul.li_4")
          %li= t("for_phone_page.ul.li_5")

        %h2= t("for_phone_page.how_to_start.title")
        %p= raw t('for_phone_page.how_to_start.text', signin_link: link_to(t('for_phone_page.how_to_start.signin_link'), interpretation_calls_path))
        #user_form{style: "margin-bottom: 40px;"}
          %form#create_new_user{action: user_registration_path, method: :post, class: 'begin_form'}
            %input{name: "is_phone_signup", value: true, type: :hidden}
            .controls
              %input{name: 'user[name]', placeholder: t("for_phone_page.form.name"), type: 'text', class: 'base-input'}
            .controls
              %input{name: 'user[surname]', placeholder: t("for_phone_page.form.surname"), type: 'text', class: 'base-input'}
            .controls
              %input{name: 'user[email]', placeholder: t("for_phone_page.form.email"), type: 'text', class: 'base-input'}
            .controls
              %input{name: 'user[password]', placeholder: t("for_phone_page.form.password"), type: 'password', class: 'base-input'}
            .controls
              %input{name: 'user[phone]', placeholder: t("for_phone_page.form.phone"), type: 'text', class: 'base-input'}
            .controls
              = render partial: 'phone/city_selector'
            .clear
            = submit_tag t("for_interpreters_page.form.submit"), class: 'base-input-submit'
      = render "interpretation_calls/app_store_link"
    .clear
    = render "interpretation_calls/app_store_footer"

app/views/home/phone_talking.html.haml
- content_for :description do
  .mobile-hide= t("service_types.title")

- [:meta_description, :title].each do |n|
  - content_for n do
    = t("service_pages.phone_talking.title") 

- content_for :back_link do
  = link_to t("help_menu.back_link"), root_path, class: 'back_link'

- content_for :body do
  .main_content
    .about_sidebar
      = render partial: 'home/help_menu'
    .about_content
      .about_type_img_wrapper
        = image_tag 'help/tel.png', class: 'img', alt: ''
        .text
          .text_inner= t("service_pages.phone_talking.title")
      .about_article= raw t("service_pages.phone_talking.text")
      = link_to t("help_menu.find_interpreter"), phone_path, class: 'intranet-button'
    .clear

app/views/home/protocol_translation.html.haml
- content_for :description do
  .mobile-hide= t("service_types.title")

- [:meta_description, :title].each do |n|
  - content_for n do
    = t("service_pages.protocol_translation.title")

- content_for :back_link do
  = link_to t("help_menu.back_link"), root_path, class: 'back_link'

- content_for :body do
  .main_content
    .about_sidebar
      = render partial: 'home/help_menu'
    .about_content
      .about_type_img_wrapper
        = image_tag 'help/protoсol.jpg', class: 'img', alt: ''
        .text
          .text_inner= t("service_pages.protocol_translation.title")
      .about_article= raw t("service_pages.protocol_translation.text")
      = render 'goto_search_button'
    .clear

app/views/home/robots.text.erb
User-agent: *
Disallow:
Sitemap: <%= sitemap_url(locale: nil) %>

app/views/home/support_individuals.html.haml
- content_for :description do
  .mobile-hide= t("service_types.title")

- [:meta_description, :title].each do |n|
  - content_for n do
    = t("service_pages.individuals.title")

- content_for :back_link do
  = link_to t("help_menu.back_link"), root_path, class: 'back_link'

- content_for :body do
  .main_content
    .about_sidebar
      = render partial: 'home/help_menu'
    .about_content
      .about_type_img_wrapper
        = image_tag 'help/lits.png', class: 'img', alt: ''
        .text
          .text_inner= t("service_pages.individuals.title")
      .about_article= raw t("service_pages.individuals.text")
      = render 'goto_search_button'
    .clear