config/routes.rb
InterpretersFrontend::Application.routes.draw do
  get "robots.txt" => "home#robots", format: :text, as: :robots
  get "sitemap.xml" => "home#sitemap", format: :xml, as: :sitemap
  get "/404", :to => "errors#error_404"
  get "/500", :to => "errors#error_500"
  put 'translated_review', to: 'client_reviews#translated_review'
  put 'original_review', to: 'client_reviews#original_review'
  
  get "/translations/:locale", to: "translations#show"

  scope "(:locale)", locale: /#{I18n.available_locales.join("|")}/ do
    spa_index = "spa#index"
    get "/spa_login", to: spa_index
    get "/translation", to: spa_index
    get "/translation_orders/new", to: spa_index
    get "/translation_orders/:id", to: spa_index
    get "/translation_orders/:id/completed", to: spa_index

    scope :spa, as: :spa do
      get "/", to: spa_index

      get "/searches", to: spa_index
      get "/searches/:id", to: spa_index
      get "/searches/:search_id/interpreters/:id", to: spa_index

      get "/orders", to: spa_index
      get "/orders/new", to: spa_index
      get "/orders/:id", to: spa_index
      get "/orders/:id/completed", to: spa_index

      get "/interpretation_calls", to: spa_index
      get "/interpretation_calls/new", to: spa_index
      get "/interpretation_calls/:id", to: spa_index

      get "/phone", to: spa_index
    end

    root :to => 'searches#new'

    # TODO: Move it to better place
    # get 'new_translation_order', to: 'translation_requests#new_translation_order', as: :new_translation_order
    # get 'show_translation_order', to: 'translation_requests#show_translation_order', as: :show_translation_order

    resource :personal_account, only: "show" do
      get "orders/:id", action: "show_order", as: :order
      get "orders/:id/voucher", action: :voucher, as: :voucher
      get "orders/:id/receipt", action: :receipt, as: :receipt
      get "orders/:id/invoice", action: :invoice, as: :invoice
      get "orders/:id/request_contacts", action: :request_contacts, as: :request_contacts
      get "searches", action: :searches, as: :searches
    end

    resource :jwt, only: "show"

    resources :call_promos, only: [:show]

    resources :interpretation_calls, only: [:index, :show, :new, :create] do
      member do
        get 'cancel'
        get 'start'
        get "complete"
        get "process_payment"
        scope module: :interpretation_calls do
          resource :duration, only: [:show]
          resource :external_numbers, only: [:create]
        end
      end
    end

    resource :twilio_token, only: [:show]

    resources :call_searches, controller: :interpretation_call_searches, only: [:new, :show, :create] do
      member do
        resources :available_questionnaires, only: [:index], module: :interpretation_call_searches
      end
    end

    resources :interpreter_inquiries, only: [:create]

    resources :partners, only: [:create]

    post 'orders/new', to: 'orders#new', as: :new_order
    get 'orders/new', to: 'orders#new'
    get 'orders/validate_email', to: 'orders#validate_email', as: :validate_email
    resources :orders, except: [:update, :destroy] do
      get 'complete', to: 'orders#complete', as: :complete
      get 'show_to_client', to: 'orders#show_to_client', as: :show_to_client
      member do
        post 'confirm_replacement'
        post 'cancel'
      end
    end

    scope :sms_service do
      post 'send_code', :to => 'orders#send_sms'
      post 'verification_code', :to => 'orders#verification_sms_code'
    end

    get '/searches/language_selector', to: 'searches#language_selector'
    get '/searches/your_language_selector', to: 'searches#your_language_selector'
    get '/searches', to: "searches#create"
    get '/new_partner_search', to: "searches#create"
    get '/amp/searches/update/:id', to: "searches#update", as: "amp_update_search"

    resources :searches do
      get 'partner_search_form', on: :collection
      post '/:id', action: :update, on: :collection
      get 'more_interpreters', to: 'searches#more_interpreters'
      get 'mini_more_interpreters', to: 'searches#mini_more_interpreters'
      get 'interpreter/:interpreter_id', to: 'searches#show_interpreter', as: :interpreter
    end

    resources :payments, only: [:new, :create]

    resources :client_reviews, only: [:update, :index]

    get 'payments/payonline/approve', to: 'payments#payonline_approve'
    get 'payments/payonline/decline', to: 'payments#payonline_decline'
    get 'payments/paypal/express_checkout/:order_id', to: "payments#paypal_express_checkout", as: :paypal_express_checkout_order
    get 'payments/paypal/complete/:order_id', to: 'payments#paypal_complete'
    get 'payments/braintree/sale/:order_id', to: 'payments#braintree_sale', as: :braintree_sale

    get 'payments/bluesnap/sale/:order_id', to: 'payments#bluesnap_sale', as: :bluesnap_sale
    #authenticated :user do
    #  root :to => 'home#dashboard', as: :authenticated_root
    #end

    # get 'dashboard', to: 'home#dashboard'
    get 'help', to: 'home#info'
    get 'help/about', to: 'home#about', as: :about
    get 'help/info', to: 'home#info', as: :info
    get 'help/help_interpreter', to: 'home#help_interpreter', as: :help_interpreter
    get 'interpreter_inquiries', to: 'home#help_interpreter'
    get 'help/for_clients', to: 'home#for_clients', as: :for_clients
    get 'help/for_affiliates', to: 'home#for_affiliates', as: :for_affiliates
    get 'help/terms_conditions', to: 'home#terms_conditions', as: :terms_conditions
    get 'help/services/guide', to: 'home#services_guide', as: :services_guide
    get 'help/services/escort_delegations', to: 'home#escort_delegations', as: :escort_delegations
    get 'help/services/interview', to: 'home#interview', as: :interview
    get 'help/services/clinic_consultation', to: 'home#clinic_consultation', as: :clinic_consultation
    get 'help/services/press_conferences', to: 'home#press_conferences', as: :press_conferences
    get 'help/services/support_individuals', to: 'home#support_individuals', as: :support_individuals
    get 'help/services/conversation', to: 'home#conversation', as: :conversation
    get 'help/services/presentation', to: 'home#presentation', as: :presentation
    get 'help/services/protocol_translation', to: 'home#protocol_translation', as: :protocol_translation
    get 'help/services/seminar_conference', to: 'home#seminar_conference', as: :seminar_conference
    get 'help/services/judicial_translation', to: 'home#judicial_translation', as: :judicial_translation
    get 'help/services/phone_talking', to: 'home#phone_talking', as: :phone_talking
    get 'help/services/celebrations', to: 'home#celebrations', as: :celebrations
    get 'help/services/exhibition', to: 'home#exhibition', as: :exhibition
    get 'help/privacy_policy', to: 'home#privacy_policy', as: :privacy_policy
    get 'help/support', to: 'client_support_tickets#new', as: :support
    get 'phone', to: 'home#phone', as: :phone

    get 'set_locale/:new_locale', to: "home#set_current_locale", as: :set_locale
    get 'set_current_currency/:currency', to: "home#set_current_currency", as: :set_current_currency

    resources :client_support_tickets, only: [:create]
    resources :interpreter_client_tickets, only: [:create]

    devise_for :users, controllers: { registrations: 'registrations', sessions: 'sessions'}

    resources :users
    post 'user_create_and_mail', to: 'users#create_and_mail'
    post 'interpreter_create_and_mail', to: 'interpreters#interpreter_create_and_mail'

    get ':city_name/:id', to: "searches#show", as: :search_city
    get ':city_name/:search_id/interpreter/:interpreter_id', to: "searches#show_interpreter", as: :search_interpreter_city
  end

  namespace :api do
    resources :tokens, only: [:create, :destroy]

    resources :countries, only: [:index] do
      get 'cities', to: 'countries#cities'
    end

    resources :cities do
      get 'interpreters', to: 'cities#interpreters'
    end
    get 'my_cities', to: 'cities#my_cities'


    # LISTS
    resources :service_types, only: [:index, :show]
    resources :languages, only: [:index, :show]
  end

  #get '/uploads/questionnaire/photo/:img/:img', to: redirect('/img/1.png')

end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  require 'rest_client'
  skip_before_filter :verify_authenticity_token, :only => [:create]
  before_action :set_default_request_format, only: [:new, :show, :show_interpreter]

  def show
    response.headers.delete "X-Frame-Options"
    id = params[:id]
    search = Search.find(id)
    unless search.url_city_name == params[:city_name]
      return redirect_to search_city_path(search.url_city_name_escaped, id, locale: params[:locale], format: params[:format]), status: 301
    end
    return unless stringify_json_parameters("#{ENV['API_BASE_URL']}/searches/#{id}.json", 'get', params)
    @show_currency_select = true
    if !@search.filter.sort_by_price.blank? and @free_interpreters
      if @search.filter.sort_by_price.upcase == 'ASC'
        @free_interpreters.sort_by!{|v| v.price}
      elsif @search.filter.sort_by_price.upcase == 'DESC'
        @free_interpreters.sort_by!{|v| v.price}.reverse!
      end
    end
  end

  def update
    id = params[:id]
    return unless stringify_json_parameters("#{ENV['API_BASE_URL']}/searches/#{id}.json", 'post', params)
    request.query_parameters.delete("clear_date")
    redirect_to search_path(@id, request.query_parameters)
  end

  def show_interpreter
    begin
      @show_currency_select = true
      interpreter_id = params[:interpreter_id]
      search_id = params[:search_id]
      User.find(interpreter_id)

      search = Search.find(search_id)
      if search.nearest_interval.since < DateTime.now.utc
        return redirect_to search_city_path(search.url_city_name_escaped, search.id, locale: params[:locale])
      end

      unless search.url_city_name == params[:city_name]
        return redirect_to search_interpreter_city_path(search.url_city_name_escaped, search_id, interpreter_id, locale: params[:locale], show_contact_form: params[:show_contact_form], format: params[:format]), status: 301
      end
      @ticket = InterpreterClientTicket.new(ic_ticket_params)
      @ticket.messages.build
      return unless stringify_json_parameters("#{ENV['API_BASE_URL']}/searches/#{search_id}/interpreter/#{interpreter_id}.json", 'get')
      @contacts_available = current_user.try(:interpreter_contacts_available?, User.find(interpreter_id))
    rescue
      @search = Search.find(params[:search_id])
      @city = @search.city 
      @questionnaires = Questionnaire.where(user_id: @search.free_interpreters_ids.split(',')).
                                      order('commission DESC, id ASC').
                                      where.not(user_id: params[:interpreter_id]).
                                      limit(5)
      render 'error_500'
    end
  end

  def new
    set_partner_id
    return unless stringify_json_parameters("#{ENV['API_BASE_URL']}/searches/new.json", 'get', params)
    set_cities_countries_count
    @on_home_page = true
  end

  def more_interpreters
    my_params = {page: params[:page], busy_int: params[:busy_int],  another_int: params[:another_int]}
    return unless stringify_json_parameters("#{ENV['API_BASE_URL']}/searches/#{params[:search_id]}/show_more_interpreters", 'get', my_params)
    render 'show.js'
  end

  def mini_more_interpreters
    return unless stringify_json_parameters("#{ENV['API_BASE_URL']}/searches/#{params[:search_id]}/min_show_more_interpreters", 'get', {page: params[:page], id: params[:current_id]})
    render 'show_interpreter.js'
  end

  def edit
  end

  def create
    return unless stringify_json_parameters("#{ENV['API_BASE_URL']}/searches.json", 'post', params)
    #if !stringify_json_parameters("#{ENV['API_BASE_URL']}/searches.json", 'post', params)
    #  redirect_to new_search_path and return
    #end
    set_partner_id
    if @errors
      respond_to do |f|
        f.html {redirect_to root_path}
        f.amp  {render 'new'}
      end
    else 
      redirect_to search_city_path(@search.url_city_name_escaped, @search.id, locale: params[:locale], format: params[:format])
    end
  end

  def language_selector
    return unless stringify_json_parameters("#{ENV['API_BASE_URL']}/searches/language_selector.json", 'get', params)
    render partial: 'searches/form/language_selector'
  end

  def your_language_selector
    return unless stringify_json_parameters("#{ENV['API_BASE_URL']}/searches/your_language_selector.json", 'get', params)
    render partial: 'searches/form/your_language_selector'
  end

  def partner_search_form
    return redirect_to root_path unless PartnerAccount.find_by_id(params[:partner_id])
    response.headers.delete "X-Frame-Options"
    @search = Search.new
    render layout: 'search_form'
  end

  private
    # Never trust parameters from the scary internet, only allow the white list through.
    def search_params
      params.require(:search).permit(:city_id, :language_id, :your_language_id, :filter_id,
                                     intervals_attributes: [:since, :to],
                                     filter_attributes: [:services, :specializations, :price_min, :price_max, :sort_by_price, :sort_by_level, :sort_by_updated_at])
    end

    def ic_ticket_params
      result = {search_id: params[:search_id]}
      if params[:interpreter_client_ticket]
        result.merge! params.require(:interpreter_client_ticket).permit(:name, :email, :phone)
      end
      result
    end
end

app/helpers/searches_helper.rb
module SearchesHelper
  def interpreters_counter
    Questionnaire.count
  end
  def cities_counter
    Questionnaire.select(:main_city_id).distinct.count
  end
  def countries_counter
    Questionnaire.select("countries.id").joins(main_city: [:country]).distinct.count
  end
  # def searches_language_selector_path
  #   '/searches/language_selector'
  # end
  # def search_path(search_id)
  #   '/searches/' + search_id.to_s
  # end
  # def search_interpreter_path(search_id, interpreter_id)
  #   '/searches/' + search_id.to_s + '/interpreter/' + interpreter_id.to_s
  # end


end

app/views/searches/_interpreter_detail.html.haml
- q_name = "#{l_questionnaire(:name)} #{shorten_surname(@questionnaire.surname)}"
- langs = "#{@search.language.locale}-#{@search.your_language.locale}"
.cart_block
  .interpreter-info-wrapper

    = image_tag @questionnaire.photo_url, class: 'cart_photo', alt: t("interpreter.in_city", city: @in_city, name: q_name)
    .info_wrapper
      %meta{content: t("show_interpreter.title", city: @in_city, interpreter: q_name, langs: langs)}
      .name= q_name
      %h2.prof{style: "margin:0;padding:0"}=  t("interpreter.title_city", city: @in_city)

      .left-right-wrapper
        .right
          %span.info-link-wrapper
            %a.experience_event.info_link{href: '#', 'data-id' => @questionnaire.id}
              #{t("interpreter.events")} (#{@questionnaire.experience_event_count})
              %i.sort-right-arrow
          %span.info-link-wrapper
            %a.experience.info_link{href: '#', 'data-id' => @questionnaire.id}
              #{t("interpreter.experience")} (#{t('years', count:  @questionnaire.experience_years)})
              %i.sort-right-arrow
          %span.info-link-wrapper
            %a.recommendations.info_link{href: "#", 'data-id' => @questionnaire.id}
              #{t("interpreter.recommendations")}
              %i.sort-right-arrow
          - if @questionnaire.video_yt_id
            %span.info-link-wrapper
              %a.youtube-link.info_link.show_dialog{data: {dialog_id: "video_dialog", dialog_title: t("show_interpreter.dialogs.youtube_title")}}
                = t("show_interpreter.youtube_link")
                %i.sort-right-arrow
            #video_dialog.my_dialog{style: "display: none;"}
              %iframe{title: "Interpreter Video", class: "youtube-player", type: "text/html", width: 460, height: 240, src: "https://www.youtube.com/embed/#{@questionnaire.video_yt_id}", frameborder: 0, allowFullScreen: ''}
        .left
          %span.info-link-wrapper
            %a.level.info_link{href: "#", 'data-id' => @questionnaire.id}
              %span.questionnaire-stars{class: questionnaire_stars_class(@questionnaire.score)}
                - if @questionnaire.client_reviews_count > 0
                  %span.client-reviews-count (#{@questionnaire.client_reviews_count})
              %i.sort-right-arrow
          %span.info-link-wrapper
            %a.education.info_link.show_dialog{data: {dialog_id: "education_dialog", dialog_title: t("show_interpreter.dialogs.education_title")}}
              = t("interpreter.education")
              = "(#{@questionnaire.educations.count})"
              %i.sort-right-arrow
          #education_dialog.my_dialog{style: "display:none;"}
            - @questionnaire.educations.each do |e|
              %p
                %b #{e.name}:
                %br
                = t("time.since_word")
                %u= e.begin_date
                = t("time.to_word")
                %u= e.end_date
                %br
                - if e.verification_image
                  = image_tag e.verification_image
          - if @questionnaire.verified
            %span.info-link-wrapper
              %a.verified_profile.info_link.show_dialog{data: {dialog_id: "verified_contacts_dialog", dialog_title: t("show_interpreter.dialogs.profile_title")}}
                = t("interpreter.verified_profile")
                %i.sort-right-arrow
            #verified_contacts_dialog.my_dialog{style: "display:none;"}
              %h3.dialog-header= t("show_interpreter.dialogs.checked_and_confirmed")
              %p.check-text= t("show_interpreter.dialogs.passport")
              %p.check-text= link_to t("show_interpreter.dialogs.documents"), "#", class: "close-dialog show_dialog", data: {"dialog-id" => "education_dialog", "close-dialog-id" => "verified_contacts_dialog", dialog_title: t("show_interpreter.dialogs.education_title")}
          %span.info-link-wrapper
            %a.verified_contacts.info_link.show_dialog{data: {dialog_id: "verified_profile_dialog", dialog_title: t("show_interpreter.dialogs.contacts_title")}}
              = t("interpreter.verified_contacts")
              %i.sort-right-arrow
          #verified_profile_dialog.my_dialog{style: "display:none;"}
            %h3.dialog-header= t("show_interpreter.dialogs.checked_and_confirmed")
            %p.check-text
              - if @contacts_available
                = t("show_interpreter.dialogs.email_full", email: @questionnaire.email)
              - else
                = t("show_interpreter.dialogs.email_address", domain: @questionnaire.email.split('.').last)
            %p.check-text
              - if @contacts_available
                = t("show_interpreter.dialogs.phone_full", phone: @questionnaire.mobile_phone)
              - else
                = t("show_interpreter.dialogs.phone", last_two: @questionnaire.mobile_phone.last(2))
            - unless @contacts_available
              %p
                - confirmation = link_to(t("show_interpreter.dialogs.order_confirmation"), "#available-serivces", class: "close-dialog", "data-close-dialog-id" => "verified_profile_dialog")
                = raw t("show_interpreter.dialogs.contacts_available", confirmation: confirmation)
    .clear
  .photo-border
  .clear
  - if @questionnaire.response_rate > 0
    %span.response-stats
      #{t("show_interpreter.response_rate")}:
      %span.green-text #{@questionnaire.response_rate}%
    %span.response-stats
      #{t("show_interpreter.avg_response_time.title")}:
      %span.green-text= t("show_interpreter.avg_response_time.#{@questionnaire.avg_response_time}")
  .clear
  = render "interpreter_client_tickets/new", ticket: @ticket, interpreter_id: @questionnaire.user_id, additional_text: t("show_interpreter.ticket_text"), on_search_page: true
  .clear
  .desc
    = l_questionnaire(:short_summary)
  .desc
    = l_questionnaire(:summary)
.info_block
  .title= t("show_interpreter.specializations")
  = @questionnaire.specializations_to_sentence
.info_block
  .title= t("show_interpreter.language_pairs")
  = @questionnaire.language_pairs_to_sentence

- if @search.busy_interpreters_ids.include? @questionnaire.user_id
  .result_trans_wrapper
    .more_results
      = t("show_interpreter.unavailable")
      = link_to t("show_interpreter.edit_search"), search_path(@search.id)
- else
  - clear_date_path = search_city_path(@search.url_city_name_escaped, @search.id, clear_date: true)
  %table.service_table#available-serivces
    %thead
      %tr
        %td
          = t("show_interpreter.available_services", period: @search.selected_period)
          = link_to t("search_page.change_date"), clear_date_path, data: {"no-turbolink" => true}, class: "change-date-link"
        %td
          - hours = t("hours", count: @search.duration_int)
          - if I18n.locale == :ja
            = t("show_interpreter.price", hours: hours)
          - else
            = t("show_interpreter.price")
            %br
            = t("for")
            = hours
        %td
          %span= t("show_interpreter.order")
    %tbody
      - @services.each do |service|
        - service_price = convert_to_current_currency(service.calculated_price, @questionnaire.currency_code)
        %tr
          %td
            %span{style: "text-decoration:none; font-family: 'robotobold'; display: inline-block"}= service_link(service.service_type)
            = t("show_interpreter.person_count", count: service.group_size) unless service.group_size.blank?
            .service-links
              - unless service.additional_cost.blank?
                .service-link.additional-cost{"data-text" => service.additional_cost}= t("show_interpreter.additional_services")
              - if service.cancellation
                .service-link.cancellation{"data-text" => t("show_interpreter.free_cancellation_text", hours: service.cancellation)}= t('show_interpreter.free_cancellation')
              - if service.discount
                .discount
                  = t("show_interpreter.discount")
                  = service.discount
                  \%
          %td.pr
            %span.price
              = service_price
            = link_to t("show_interpreter.order_button"), new_order_path(order: {interpreter_id: @interpreter.user_id, search_id: @search.id, service_id: service.id}), method: :post, class: "mob-link new-order-button", "data-clear-date-path" => clear_date_path,  "data-modal-content" => "#service-confirm-modal-#{service.id}"
          %td
            = simple_form_for :order, url: new_order_path(order: {interpreter_id: @interpreter.user_id, search_id: @search.id, service_id: service.id}) do |f|
              = f.button :submit, t("show_interpreter.order_button"), class: 'link pull-right new-order-button', "data-clear-date-path" => clear_date_path, "data-modal-content" => "#service-confirm-modal-#{service.id}"
        .hidden{id: "service-confirm-modal-#{service.id}"}
          %p
            = t("show_interpreter.confirm_modal.date")
            %b= @search.selected_period
          %br
          %p= t("show_interpreter.confirm_modal.service", service: l_object(:name, service.service_type), city: @in_city)
          %p
            = t("show_interpreter.confirm_modal.languages")
            #{@search.language.name} - #{@search.your_language.name}
          %p
            = t("show_interpreter.confirm_modal.price")
            %b= service_price
        -# TODO: dynamic pair of languages; translations (i18n)
      %tr
        %td
          %span.blue_text= t("show_interpreter.translation")
        %td{colspan: "2"}
          = link_to t("show_interpreter.get_quote"), translation_path(source_language: @search.your_language.locale, target_language: @search.language.locale), class: 'btn link get_quote'

  .star_text
    = t("show_interpreter.star_text")

app/views/searches/_questionnaire_mini.html.haml
.alike_trans_block.search_result{'data-interpreter-id' => questionnaire_mini.id}
  / .photo-wrapper
  = image_tag questionnaire_mini.photo_url, class: 'img'
  .desc
    = link_to "#{l_questionnaire(:name, questionnaire_mini)} #{shorten_surname(questionnaire_mini.surname)}", search_interpreter_path(@search.id, questionnaire_mini.user_id), class: 'name'
    %span
      .price
        = convert_to_current_currency(questionnaire_mini.price.to_i, questionnaire_mini.currency_code)
    %a.experience.info_link{href: '#', 'data-id' => questionnaire_mini.id} #{t("interpreter.experience")} (#{t('years', count: questionnaire_mini.experience_years)})
    %a.education-remote.info_link{href: '#', 'data-id' => questionnaire_mini.id} #{t("interpreter.education")} (#{questionnaire_mini.educations_count})
  .clear

app/views/searches/_search_form.html.haml
.find_translator_wrapper
  .title
    = t('search_form.title')
  .form_wrapper#search_form_wrapper
    = simple_form_for :search, url: searches_path, html: {id: 'base_form_search'}  do |f|
      = f.hidden_field :user_id, value: current_user.id if current_user.present?
      .label
        %span.lab
          = t('search_form.where')
        %span.error
        = f.error :city
        = render partial: 'searches/form/city_selector'
      .label
        %span.lab
          = t('search_form.when')
        %span.error
        = f.error :intervals
        = render partial: 'searches/form/date_selector'
      .label
        %span.lab
          = t('search_form.language')
        %span.error
        = f.error :language_id
        = render partial: 'searches/form/language_selector'
      .your_lang
        = t('search_form.your_language')
        = render partial: 'searches/form/your_language_selector'

      = f.submit t('search_form.button'), class: 'sub_bot'
  .clear

app/views/searches/edit.html.haml
= render "search_form"

app/views/searches/show_interpreter.html.haml
- @questionnaire = @interpreter
- city_name = l_object(:name, @search.city)
- @city_name = city_name
- @in_city = city_name_in_loct_case(@search.city, city_name)
- name = "#{l_questionnaire(:name)} #{shorten_surname(@questionnaire.surname)}"
- langs = "#{@search.language.locale}-#{@search.your_language.locale}"

- title = t("show_interpreter.title", city: @in_city, interpreter: name, langs: langs)

- content_for :amp_link do
  %link{rel: "amphtml", href: url_for(format: :amp, only_path: false)}

- content_for(:title){ title }

- content_for(:og_title) { title }

- content_for(:og_description){ title }

- @mobile_hide_description = true
- content_for :description do
  = t("show_interpreter.service_select", city: @in_city)
- content_for :meta_description do
  #{t("show_interpreter.desc_addition", langs: langs, city: @in_city)} #{l_questionnaire(:short_summary)}

- content_for :keywords do
  = t("show_interpreter.keywords", city: @in_city)

- content_for :back_link do
  = link_to t("show_interpreter.back_link", city: @in_city), search_path(@search.id), class: 'back_link'

- content_for :body do
  %input{type: 'hidden', value: @search.id, id: 'search_id'}
  %input{type: 'hidden', value: @interpreter.id, id: 'interpreter_id'}
  .result_mob_menu
    %ul.show-inter-mob-tabs{style: "display: table;"}
      %li.act
        %a{tabindex: 0}= t("show_interpreter.service_select", city: @in_city)
      %li 
        %a{tabindex: 1}= t("show_interpreter.similar_interpreters") 
  .green_line
  .main_content
    .cart_sidebar.tab-toggle.similar-interpreters{"data-tabindex" => 1}
      .alike_trans_wrapper
        .alike_trans_title
          = t("show_interpreter.similar_interpreters")
        .alike_trans_inner
          .is_cont
            - unless @similar_interpreters.blank?
              = render partial: 'questionnaire_mini', collection: @similar_interpreters
              - if @min_page_count and @min_page_count.to_i > 1
                .loading-bar.show-more-mini{'data-page_count' => @min_page_count, 'data-current_page' => 1, 'data-current_id' => @interpreter.id, 'data-url' => search_mini_more_interpreters_path(@search.id)}
                  = t("show_interpreter.load_more")
      .why-interpreters.mobile-hide
        = raw t("show_interpreter.why_itravel_block") 

        = link_to t("show_interpreter.learn_more"), for_clients_path, class: "more-info-link", target: "_blank"

    .cart_content.tab-toggle{"data-tabindex" => 0}
      
      %br
      .cart_country_wrapper
        .country #{@search.city.country}, #{l_object :name, @search.city}
        #{t("show_interpreter.selected_period", intervals: helper_intervals_text(@search))}

      = render partial: 'interpreter_detail'

      .how_order_block
        %h3.title{style: "margin:0; padding: 0;"}
          = t("show_interpreter.how_to_order.title", city: @in_city)
        = raw t("show_interpreter.how_to_order.text")
      .cart_sidebar.mobile-show
        .why-interpreters
          = raw t("show_interpreter.why_itravel_block")
          = link_to t("show_interpreter.learn_more"), for_clients_path, class: "more-info-link", target: "_blank"

      .client-reviews-wrapper

    .clear
  %span.viewers-count-message{style: "display: none;"}= t("show_interpreter.viewers_count", count: rand(1..5))

  :javascript
    $.get("#{client_reviews_path(questionnaire_id: @questionnaire.id)}");

  / = render "searches/google_product_info", services: @services, questionnaire: @questionnaire, in_city: @in_city, interpreter_name: name, langs: langs

  - if @services.any?
    - product_info = generate_google_product_info(services: @services, questionnaire: @questionnaire, in_city: @in_city, interpreter_name: name, langs: langs)

    %script{type: "application/ld+json"}
      :plain
        #{raw JSON.generate(product_info)}