config/routes.rb
InterpretersFrontend::Application.routes.draw do
  get "robots.txt" => "home#robots", format: :text, as: :robots
  get "sitemap.xml" => "home#sitemap", format: :xml, as: :sitemap
  get "/404", :to => "errors#error_404"
  get "/500", :to => "errors#error_500"
  put 'translated_review', to: 'client_reviews#translated_review'
  put 'original_review', to: 'client_reviews#original_review'
  
  get "/translations/:locale", to: "translations#show"

  scope "(:locale)", locale: /#{I18n.available_locales.join("|")}/ do
    spa_index = "spa#index"
    get "/spa_login", to: spa_index
    get "/translation", to: spa_index
    get "/translation_orders/new", to: spa_index
    get "/translation_orders/:id", to: spa_index
    get "/translation_orders/:id/completed", to: spa_index

    scope :spa, as: :spa do
      get "/", to: spa_index

      get "/searches", to: spa_index
      get "/searches/:id", to: spa_index
      get "/searches/:search_id/interpreters/:id", to: spa_index

      get "/orders", to: spa_index
      get "/orders/new", to: spa_index
      get "/orders/:id", to: spa_index
      get "/orders/:id/completed", to: spa_index

      get "/interpretation_calls", to: spa_index
      get "/interpretation_calls/new", to: spa_index
      get "/interpretation_calls/:id", to: spa_index

      get "/phone", to: spa_index
    end

    root :to => 'searches#new'

    # TODO: Move it to better place
    # get 'new_translation_order', to: 'translation_requests#new_translation_order', as: :new_translation_order
    # get 'show_translation_order', to: 'translation_requests#show_translation_order', as: :show_translation_order

    resource :personal_account, only: "show" do
      get "orders/:id", action: "show_order", as: :order
      get "orders/:id/voucher", action: :voucher, as: :voucher
      get "orders/:id/receipt", action: :receipt, as: :receipt
      get "orders/:id/invoice", action: :invoice, as: :invoice
      get "orders/:id/request_contacts", action: :request_contacts, as: :request_contacts
      get "searches", action: :searches, as: :searches
    end

    resource :jwt, only: "show"

    resources :call_promos, only: [:show]

    resources :interpretation_calls, only: [:index, :show, :new, :create] do
      member do
        get 'cancel'
        get 'start'
        get "complete"
        get "process_payment"
        scope module: :interpretation_calls do
          resource :duration, only: [:show]
          resource :external_numbers, only: [:create]
        end
      end
    end

    resource :twilio_token, only: [:show]

    resources :call_searches, controller: :interpretation_call_searches, only: [:new, :show, :create] do
      member do
        resources :available_questionnaires, only: [:index], module: :interpretation_call_searches
      end
    end

    resources :interpreter_inquiries, only: [:create]

    resources :partners, only: [:create]

    post 'orders/new', to: 'orders#new', as: :new_order
    get 'orders/new', to: 'orders#new'
    get 'orders/validate_email', to: 'orders#validate_email', as: :validate_email
    resources :orders, except: [:update, :destroy] do
      get 'complete', to: 'orders#complete', as: :complete
      get 'show_to_client', to: 'orders#show_to_client', as: :show_to_client
      member do
        post 'confirm_replacement'
        post 'cancel'
      end
    end

    scope :sms_service do
      post 'send_code', :to => 'orders#send_sms'
      post 'verification_code', :to => 'orders#verification_sms_code'
    end

    get '/searches/language_selector', to: 'searches#language_selector'
    get '/searches/your_language_selector', to: 'searches#your_language_selector'
    get '/searches', to: "searches#create"
    get '/new_partner_search', to: "searches#create"
    get '/amp/searches/update/:id', to: "searches#update", as: "amp_update_search"

    resources :searches do
      get 'partner_search_form', on: :collection
      post '/:id', action: :update, on: :collection
      get 'more_interpreters', to: 'searches#more_interpreters'
      get 'mini_more_interpreters', to: 'searches#mini_more_interpreters'
      get 'interpreter/:interpreter_id', to: 'searches#show_interpreter', as: :interpreter
    end

    resources :payments, only: [:new, :create]

    resources :client_reviews, only: [:update, :index]

    get 'payments/payonline/approve', to: 'payments#payonline_approve'
    get 'payments/payonline/decline', to: 'payments#payonline_decline'
    get 'payments/paypal/express_checkout/:order_id', to: "payments#paypal_express_checkout", as: :paypal_express_checkout_order
    get 'payments/paypal/complete/:order_id', to: 'payments#paypal_complete'
    get 'payments/braintree/sale/:order_id', to: 'payments#braintree_sale', as: :braintree_sale

    get 'payments/bluesnap/sale/:order_id', to: 'payments#bluesnap_sale', as: :bluesnap_sale
    #authenticated :user do
    #  root :to => 'home#dashboard', as: :authenticated_root
    #end

    # get 'dashboard', to: 'home#dashboard'
    get 'help', to: 'home#info'
    get 'help/about', to: 'home#about', as: :about
    get 'help/info', to: 'home#info', as: :info
    get 'help/help_interpreter', to: 'home#help_interpreter', as: :help_interpreter
    get 'interpreter_inquiries', to: 'home#help_interpreter'
    get 'help/for_clients', to: 'home#for_clients', as: :for_clients
    get 'help/for_affiliates', to: 'home#for_affiliates', as: :for_affiliates
    get 'help/terms_conditions', to: 'home#terms_conditions', as: :terms_conditions
    get 'help/services/guide', to: 'home#services_guide', as: :services_guide
    get 'help/services/escort_delegations', to: 'home#escort_delegations', as: :escort_delegations
    get 'help/services/interview', to: 'home#interview', as: :interview
    get 'help/services/clinic_consultation', to: 'home#clinic_consultation', as: :clinic_consultation
    get 'help/services/press_conferences', to: 'home#press_conferences', as: :press_conferences
    get 'help/services/support_individuals', to: 'home#support_individuals', as: :support_individuals
    get 'help/services/conversation', to: 'home#conversation', as: :conversation
    get 'help/services/presentation', to: 'home#presentation', as: :presentation
    get 'help/services/protocol_translation', to: 'home#protocol_translation', as: :protocol_translation
    get 'help/services/seminar_conference', to: 'home#seminar_conference', as: :seminar_conference
    get 'help/services/judicial_translation', to: 'home#judicial_translation', as: :judicial_translation
    get 'help/services/phone_talking', to: 'home#phone_talking', as: :phone_talking
    get 'help/services/celebrations', to: 'home#celebrations', as: :celebrations
    get 'help/services/exhibition', to: 'home#exhibition', as: :exhibition
    get 'help/privacy_policy', to: 'home#privacy_policy', as: :privacy_policy
    get 'help/support', to: 'client_support_tickets#new', as: :support
    get 'phone', to: 'home#phone', as: :phone

    get 'set_locale/:new_locale', to: "home#set_current_locale", as: :set_locale
    get 'set_current_currency/:currency', to: "home#set_current_currency", as: :set_current_currency

    resources :client_support_tickets, only: [:create]
    resources :interpreter_client_tickets, only: [:create]

    devise_for :users, controllers: { registrations: 'registrations', sessions: 'sessions'}

    resources :users
    post 'user_create_and_mail', to: 'users#create_and_mail'
    post 'interpreter_create_and_mail', to: 'interpreters#interpreter_create_and_mail'

    get ':city_name/:id', to: "searches#show", as: :search_city
    get ':city_name/:search_id/interpreter/:interpreter_id', to: "searches#show_interpreter", as: :search_interpreter_city
  end

  namespace :api do
    resources :tokens, only: [:create, :destroy]

    resources :countries, only: [:index] do
      get 'cities', to: 'countries#cities'
    end

    resources :cities do
      get 'interpreters', to: 'cities#interpreters'
    end
    get 'my_cities', to: 'cities#my_cities'


    # LISTS
    resources :service_types, only: [:index, :show]
    resources :languages, only: [:index, :show]
  end

  #get '/uploads/questionnaire/photo/:img/:img', to: redirect('/img/1.png')

end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_filter :authenticate_user!, except: [:new_payment, :new, :create, :complete, :send_sms, :verification_sms_code, :show_to_client, :validate_email]
  before_action :set_order, only: [:new_payment, :show, :edit, :update, :destroy, :cancel, :confirm_replacement]
  skip_before_filter :verify_authenticity_token, only: [:new, :create, :validate_email]
  before_filter :store_order_params, only: [:new, :create]
  before_action :set_default_response_format, only: [:new]

  def validate_email
    @email = params[:email]
    if @email.blank?
      render nothing: true
      return
    end
    @exists_user = User.find_by_email(params[:email])
  end

  # GET /orders
  # GET /orders.json
  def index
    @orders = current_user.orders.joins(:payment)
    render layout: "intranet"
  end

  def show_to_client
    @order = Order.unscoped.find(params[:order_id])
    @notice = 'Order details'
    render layout: "simple"
  end

  # GET /orders/1
  # GET /orders/1.json
  def show
    render layout: "intranet"
  end

  def store_order_params
    # session[:order_params] = params[:order] || session[:order_params]
  end

  # GET /orders/new
  def new
    order = Order.new(order_params)
    search = order.search
    interpreter = order.interpreter
    service = order.service
    if !service and search and interpreter
      return redirect_to search_interpreter_city_path(search.url_city_name_escaped, search.id, interpreter.id, locale: params[:locale])
    elsif (!service or !interpreter) and search
      return redirect_to search_city_path(search.url_city_name_escaped, search.id, locale: params[:locale])
    elsif !search
      return redirect_to root_path
    end

    return unless stringify_json_parameters("#{ENV['API_BASE_URL']}/orders/new_order.json", 'post', params)
    @user = current_user
  end

  # GET /orders/1/edit
  def edit
  end

  # POST /orders
  # POST /orders.json
  def create
    params[:phone_confirmed] = true#session[:phone_confirmed]
    params[:order][:client_currency_code] ||= session[:current_currency]
    params[:order][:locale] = params[:locale]
    params[:order][:partner_account_id] = cookies[:partner_id]

    if request.location
      params[:order][:city_name] ||= request.location.city 
    end

    if current_user
      params[:order][:client_id] = current_user.id
      params[:order].delete(:client_attributes)
    end
    submit_params = params.dup 
    submit_params.delete("X-Requested-With")
    submit_params.delete("X-Http-Accept")
    submit_params.delete('remotipart_submitted')
    return unless stringify_json_parameters("#{ENV['API_BASE_URL']}/orders.json", 'post', submit_params)
    params[:order][:file] = nil
    if @order_errors
      @error = ("Erorrs:<br/>" + @order_errors.join('<br/>')).html_safe
      # Reconstruct request order parameters:
      order_parameters = ActionController::Parameters.new order:
        {
          search_id: params[:order][:search_id],
          interpreter_id: params[:order][:interpreter_id],
          service_id: params[:order][:service_id]
        }
      respond_to do |format|
        format.js { flash.now[:error] = @error; render 'creation_error' }
        format.html { flash[:error] = @error; redirect_to(new_order_path(order_parameters), format: :js)}
      end
      return
    end
    # If success
    respond_to do |format|
      format.js 
      format.html { redirect_to new_payment_path(order_id: @order.id) }
    end
  end

  def complete
    @order = Order.unscoped.where(id: params[:order_id]).first
    if !@order.new?
      return redirect_to order_personal_account_path(@order)
    end
    @payment = @order.payment
    @interpreter = @order.interpreter
    @questionnaire = @interpreter.questionnaire
    @city_and_country = "#{@order.search.city}"
    @language_pair = "#{@order.search.your_language} - #{@order.search.language}"
  end

  # PATCH/PUT /orders/1
  # PATCH/PUT /orders/1.json
  # def update
  #   respond_to do |format|
  #     if @order.update(order_params)
  #       format.html { redirect_to @order, notice: 'Order was successfully updated.' }
  #       format.json { head :no_content }
  #     else
  #       format.html { render action: 'edit' }
  #       format.json { render json: @order.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end

  # DELETE /orders/1
  # DELETE /orders/1.json
  # def destroy
  #   @order.destroy
  #   respond_to do |format|
  #     format.html { redirect_to orders_url }
  #     format.json { head :no_content }
  #   end
  # end

  def send_sms
    params[:sms_code] = session[:sms_code]
    return unless stringify_json_parameters("#{ENV['API_BASE_URL']}/orders/send_sms.json", 'get', params)
    session[:sms_code] = @sms_code  # @sms_code is api response
    session[:phone_number] = params[:number] # displayed on View
    render :json => { phone_number: session[:phone_number] }
  end

  def verification_sms_code
    is_code_valid = params[:verification_code].to_s == session[:sms_code].to_s
    session[:phone_confirmed] = is_code_valid
    render :json => { valid: is_code_valid }
  end

  def confirm_replacement
    if @order.awaiting_client_confirmation? and @order.client == current_user
      stringify_json_parameters("#{ENV['API_BASE_URL']}/orders/confirm_replacement.json", 'post', params)
      redirect_to order_personal_account_path(@order), notice: @message
    end
  end

  def cancel
    if @order.cancellation_possible? and @order.client == current_user
      stringify_json_parameters("#{ENV['API_BASE_URL']}/orders/cancel.json", 'post', params)
    end
    redirect_to order_personal_account_path(@order), notice: @message 
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.unscoped.find(params[:id])
    end


    # Never trust parameters from the scary internet, only allow the white list through.
    def order_params
      params.require(:order).permit(:interpreter_id, :client_id, :operator_id, :search_id, :service_id, :name, :surname, :legal_form,
                                    :inn, :bank_name, :meeting_address, :detail_information, :since, :to, :phone, :company_activity,
                                    :company_address, :reporting_documents, :bik, :settlement_account, :correspondent_account,
                                    address_attributes: [:location, :city_id, :region, :zip],
                                    # card_attributes: [:first_name, :last_name, :brand, :number, :verification_value, :month, :year],
                                    client_attributes: [:name, :surname, :email, :phone, :assigned_full_name])
    end

    def set_default_response_format
      request.format = :html
    end
end

app/helpers/orders_helper.rb
module OrdersHelper
  SERVICE_PATHS = {}
  mappings = {"Переводчик на презентации" => :presentation, "Переводчик на переговорах" => :conversation, "Переводчик на выставке" => :exhibition, "Переводчик на семинаре или конференции" => :seminar_conference, "Переводчик на торжествах" => :celebrations, "Перевод экскурсий, услуги гида" => :services_guide, "Сопровождение делегаций" => :escort_delegations, "Сопровождение частных лиц" => :support_individuals, "Переводчик по телефону" => :phone_talking, "Переводчик интервью" => :interview, "Переводчик пресс-конференций" => :press_conferences, "Протокольный переводчик" => :protocol_translation, "Судебный переводчик" => :judicial_translation, "Переводчик в клинике" => :clinic_consultation}
  ServiceType.all.each do |t| 
    if path = mappings[t.ru_name]
      SERVICE_PATHS[t.id] = path 
    end
  end

  def cancel_order_text(intervals, min_time)
    tmp = intervals.map{|i| (i.since.to_datetime.to_i - DateTime.now.to_i) / 3600 }.min

    if tmp < min_time
      '<span>Бесплатная отмена заказа:</span> не предусмотрено'.html_safe
    else
      tmp = intervals.map{|i| (i.since.to_datetime)}.min.to_datetime - min_time.hours
      date = l(tmp, format: 'до %d %B %H:%M')
      text = "Возможна бесплатная отмена заказа не позднее, чем до #{date} часов до начала встречи. Отмена заказа позднее этого срока и до начала встречи, возможна только с удержанием оплаты первых двух часов услуг переводчика."
      ("<span class='cancellation' data-text='#{text}'>Бесплатная отмена заказа:</span> #{date}").html_safe
    end

  end

  def service_link(service_type)
    name = l_object(:name, service_type)
    id = service_type.id
    if (path = SERVICE_PATHS[id])
      link_to(name, send("#{path}_path"), target: "_blank")
    else 
      name 
    end
  end

  def aviasales_script_id
    locale = params[:locale].to_s
    case locale 
    when 'en'
      "c5981d2787c4b5f744335eb0348beb0f"
    when 'ru'
      "ef509ad6cb688579bc01c6346675a52e"
    end
  end
end

app/views/orders/new/_company_form.html.haml
= simple_form_for :order, :url => orders_path, multipart: true, html: { class: 'company_form order_form' }, remote: true  do |f|
  %input{ id: :interpreter_id, type: :hidden, value: params[:order][:interpreter_id], name: 'order[interpreter_id]'}
  %input{ id: :search_id, type: :hidden, value: params[:order][:search_id], name: 'order[search_id]'}
  %input{ id: :service_id, type: :hidden, value: params[:order][:service_id], name: 'order[service_id]'}
  %input{ id: :operator_id, type: :hidden, value: params[:order][:operator_id], name: "order[operator_id]"}

  .contact_info
    .title
      Информация о компании:
    .input-container
      %input{name: 'order[legal_form]', placeholder: 'Административно правовая форма', type: :text}
    .input-container
      %input{name: 'order[name]', placeholder: 'Название:', type: :text}
    .input-container
      %input{name: 'order[company_address]', placeholder: 'Юридический адрес:', type: :text}
    -#%label.other_field
      .doc
        = succeed "Получить оригиналы отчетных документов" do
          %input{name: "order[reporting_documents]", type: "checkbox"}
      %span.clear{style: "display:block;"}
    .input-container
      %input{name: 'order[phone]', placeholder: 'Телефон Компании:', type: :text}
    .input-container
      %input{name: 'order[inn]', placeholder: 'ИНН:', type: :text}

    = select_tag 'order[company_activity]', options_from_collection_for_select(@specialization_select, :id, :name), prompt: 'Сфера деятельности Компании'
    .clear
  .user_info
    .title
      Информация о заказчике услуг:
    .input-container
      %input{name: 'order[client_attributes][surname]', placeholder: 'Фамилия:', type: :text, value: "#{@user.try(:surname).to_s}", class: "#{'act_inp' unless @user.blank?}"}
    .input-container
      %input{name: 'order[client_attributes][name]', placeholder: 'Имя:', type: :text, value: "#{@user.try(:name).to_s}", class: "#{'act_inp' unless @user.blank?}"}
    .input-container
      %input{name: 'order[client_attributes][phone]', placeholder: 'Телефон для СМС уведомлений:', type: :text, value: "#{session[:phone_number]}", class: "phone-for-sms #{'act_inp' unless @user.blank?}", "data-sms-url" => send_code_path, readonly: false ? true : false}
    .input-container
      %input{name: "order[city_name]", autocomplete: "off", "placeholder" => "Город:", type: "text"}
    .input-container
      %input{name: "client[address]", placeholder: "Адрес:", type: "text"}
    - unless user_signed_in?
      .input-container
        %input.no_mrg{name: 'order[client_attributes][email]', placeholder: 'Email:', type: :text, value: "#{@user.try(:email).to_s}", class: "#{'act_inp' unless @user.blank?}"}
    .clear
  .translator_info.user_info
    .title
      Информация для переводчика:
    .input-container.addr
      %input.adr.google-address{name: 'order[meeting_address]', autocomplete: 'off', placeholder: 'Адрес встречи с переводчиком:', type: :text}
      %div.custom-dropdown
    .open_map_link.mobile-hide Указать на карте
    %textarea{cols: 10, name: 'order[detail_information]', placeholder: 'Опишите тему или вопросы встречи, скопируйте текст релиза или другую информацию (не более 1200 символов). Это позволит переводчику лучше подготовится к переводу на встрече или мероприятии', rows: 10}
    .mobile_hide
      %p{style: "display: block;font: 15px 'robotolight'; float: left;"}Добавьте файл с информацией
      = f.file_field :file
    = hidden_field_tag "order[client_currency_code]", session[:current_currency], class: "currency-field"
    .clear
  = render partial: 'orders/new/order_agreement'
  .text-center
    %input.order_form_submit{type: :submit, value: "Выбрать способ оплаты заказа"}
  .clear
  %br

app/views/orders/new/_order_agreement.html.haml
- policy_link = link_to t("order_page.personal_form.policy"), privacy_policy_path, target: "_blank"
- terms_link = link_to t("order_page.personal_form.terms"), terms_conditions_path, target: "_blank"
.order_agreement_link 
  = raw t("order_page.personal_form.agreement_text", policy: policy_link, terms: terms_link)

app/views/orders/new/_payment_block.html.haml
/ .title После оформления заказа вы будете перенаправлены на страницу партнера для совершения платежа
.payment_tabs#payment-tabs
  %span.text
    = t("order_page.payment.select")
  .tabs
    = label_tag do 
      = radio_button_tag 'payment_type', 'card'
      Visa/MasterCard
    - if @order.service.can_pay_with_cash
      = label_tag do 
        = radio_button_tag 'payment_type', 'cash'
        = t("order_page.payment.cash")
    - if @order.can_pay_with_invoice
      = label_tag do 
        = radio_button_tag 'payment_type', 'invoice'
        = t("order_page.payment.invoice")

:coffee 
  $(".payment_tabs .tabs input").styler()
  $(".payment_tabs .tabs input").on('change', ->
    $.get('#{new_payment_path(order_id: @order.id)}', $(".payment_tabs .tabs input").serialize(), null, 'script')
  )

app/views/orders/new/_personal_form.html.haml
= simple_form_for :order, :url => orders_path, multipart: true, html: { class: 'personal_form order_form' }, remote: true  do |f|
  %input{ id: :interpreter_id, type: :hidden, value: params[:order][:interpreter_id], name: "order[interpreter_id]"}
  %input{ id: :search_id, type: :hidden, value: params[:order][:search_id], name: "order[search_id]"}
  %input{ id: :service_id, type: :hidden, value: params[:order][:service_id], name: "order[service_id]"}
  %input{ id: :operator_id, type: :hidden, value: params[:order][:operator_id], name: "order[operator_id]"}

  .contact_info
    .title
      = t("order_page.personal_form.title")
    .input-container
      %input{name: "order[client_attributes][assigned_full_name]", class: "name#{'act_inp' if @user}", placeholder: t("order_page.personal_form.name"), value: (@user.try(:full_name) || @order.client.full_name), type: "text"}
    .input-container
      %input{name: "order[phone]", class: "phone-for-sms", "placeholder" => t("order_page.personal_form.sms_phone"), value: (@order.phone), type: "text", "data-sms-url" => send_code_path, readonly: false ? true : false}

    - unless user_signed_in?
      .input-container
        %input.no_mrg{name: "order[client_attributes][email]", class: "#{'act_inp' if @user}", placeholder: t("order_page.personal_form.email"), value: (@user.try(:email) || @order.client.email.downcase), type: "email", readonly: @user ? true : false   }
    .clear
  .translator_info.user_info
    .title
      = t("order_page.personal_form.info_for_interpreter")
    .input-container.addr
      %input.adr.google-address{name: "order[meeting_address]", autocomplete: "off", "placeholder" => t("order_page.personal_form.meeting_address"), type: "text"}
      %div.custom-dropdown
    .open_map_link.mobile-hide= t("order_page.personal_form.map_link")
    .map_modal.mobile-hide
      %input#map_address{type: "text", style: "width: 100%"}
      #leaflet-address-select-map{style: "width: 100%; height: 90%;"}
    .clear
    %textarea{cols: 10, name: 'order[detail_information]', placeholder: t("order_page.personal_form.detail_information"), rows: 10}
    .mobile-hide
      %p{style: "display: block;font: 15px 'robotolight'"}= t("order_page.personal_form.file_field")
      = f.file_field :file
    = hidden_field_tag "order[client_currency_code]", session[:current_currency], class: "currency-field"
    .clear
  = render partial:  'orders/new/order_agreement'
  .text-center
    %input.order_form_submit{type: "submit", value: t("order_page.personal_form.submit")}
  .clear
  %br